image = "kms:latest"
environment = "prod"
vpc_id = "vpc-24988f4d"
subnet_id = "subnet-a886b4c1"
repository_arn_aws_creds = "arn:aws:secretsmanager:eu-west-3:324777464715:secret:deploy/ddec-tXKTIn"
instance_type = "m6i.xlarge"
ssh_key_name = ""
image_eif = "kms-enclave.latest"
