//! Flattened, `MetaParameters`-backed `DKGParams`.
//!
//! This carries a [`tfhe::shortint::parameters::MetaParameters`] plus the
//! few values tfhe-rs has no concept of (`dkg_mode`, `sec`, `secret_key_deviations`).

use clap::ValueEnum;
use serde::{Deserialize, Serialize};
use statrs::distribution::{Binomial, DiscreteCDF};
use std::sync::LazyLock;
use tfhe::core_crypto::commons::ciphertext_modulus::CiphertextModulus;
use tfhe::integer::parameters::DecompositionBaseLog;
use tfhe::shortint::parameters::list_compression::ClassicCompressionParameters;
use tfhe::shortint::parameters::meta::DedicatedCompactPublicKeyParameters;
use tfhe::shortint::parameters::{
    AtomicPatternParameters, Backend, ClassicPBSParameters, CompactCiphertextListExpansionKind,
    CompactPublicKeyEncryptionParameters, CompressionParameters, DecompositionLevelCount,
    DynamicDistribution, EncryptionKeyChoice, GlweDimension, LweCiphertextCount, LweDimension,
    MetaNoiseSquashingParameters, MetaParameters, ModulusSwitchNoiseReductionParams,
    ModulusSwitchType, NoiseEstimationMeasureBound, NoiseSquashingClassicParameters,
    NoiseSquashingCompressionParameters, NoiseSquashingParameters, PBSOrder, PBSParameters,
    PolynomialSize, RSigmaFactor, ShortintKeySwitchingParameters, SupportedCompactPkeZkScheme,
    Variance,
};
use tfhe::shortint::{CarryModulus, MaxNoiseLevel, MessageModulus};

use crate::keyset_config::{KeyGenSecretKeyConfig, KeySetConfig};

pub trait AugmentedCiphertextParameters {
    // Return the minimum amount of bits that can be used for a message in each block.
    fn message_modulus_log(&self) -> u32;

    // Return the minimum amount of bits that can be used for a carry in each block.
    fn carry_modulus_log(&self) -> u32;
    // Return the minimum total amounts of availble bits in each block. I.e. including both message and carry bits
    fn total_block_bits(&self) -> u32;
}

impl AugmentedCiphertextParameters for tfhe::shortint::Ciphertext {
    // Return the minimum amount of bits that can be used for a message in each block.
    fn message_modulus_log(&self) -> u32 {
        self.message_modulus.0.ilog2()
    }

    // Return the minimum amount of bits that can be used for a carry in each block.
    fn carry_modulus_log(&self) -> u32 {
        self.carry_modulus.0.ilog2()
    }

    // Return the minimum total amounts of availble bits in each block. I.e. including both message and carry bits
    fn total_block_bits(&self) -> u32 {
        self.carry_modulus_log() + self.message_modulus_log()
    }
}

impl AugmentedCiphertextParameters for ClassicPBSParameters {
    // Return the minimum amount of bits that can be used for a message in each block.
    fn message_modulus_log(&self) -> u32 {
        self.message_modulus.0.ilog2()
    }

    // Return the minimum amount of bits that can be used for a carry in each block.
    fn carry_modulus_log(&self) -> u32 {
        self.carry_modulus.0.ilog2()
    }

    // Return the minimum total amounts of availble bits in each block. I.e. including both message and carry bits
    fn total_block_bits(&self) -> u32 {
        self.carry_modulus_log() + self.message_modulus_log()
    }
}

/// Flattened DKG parameters backed by a tfhe-rs [`MetaParameters`].
///
/// `meta` carries all the crypto parameters; the other three fields are the
/// KMS-only values that have no place in `MetaParameters`.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct DKGParams {
    /// Z64 vs Z128 sharing domain. Must be `Z128` whenever SnS is present
    /// (enforced by [`Self::check_conformance`]).
    pub dkg_mode: DkgMode,
    /// Security parameter (XOF seed size).
    pub sec: u64,
    /// All tfhe-rs crypto parameters.
    pub meta: MetaParameters,
    /// Optional Hamming-weight bound for DKG secret-key sampling.
    pub secret_key_deviations: Option<SecretKeyDeviations>,
}

/// Tells us whether the DKG should be run in Z64 or Z128
/// this is checked against the size of the underlying ring
/// when calling DKG; and used to infer the domain of the keys
/// in resharing.
#[derive(Clone, Copy, PartialEq, Serialize, Deserialize, Debug)]
pub enum DkgMode {
    Z64,
    Z128,
}

/// Parameters to specify the acceptable range for the hamming weight
/// of the secret keys generated by the DKG protocol.
/// Same parameters are used for all secret keys inside a keyset.
#[derive(Clone, Copy, PartialEq, Serialize, Deserialize, Debug)]
pub struct SecretKeyDeviations {
    /// Log2 of the acceptable failure probability
    /// Plays on how many extra bits we sample to be confident that we can indeed
    /// sample our keys within the desired HW range
    pub log2_failure_proba: i64,
    /// The HW of all keys must be in [floor((1-pmax) * len) ,(pmax)*len]
    /// (Thus 0.5 < pmax < 1.0 )
    pub pmax: f64,
}

#[derive(Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Debug, Default)]
pub struct TUniformBound(pub usize);

#[derive(Debug, Clone, Copy, strum::EnumIter, PartialEq, Eq)]
pub enum NoiseBounds {
    LweNoise(TUniformBound),
    LweHatNoise(TUniformBound),
    GlweNoise(TUniformBound),
    GlweNoiseSnS(TUniformBound),
    CompressionKSKNoise(TUniformBound),
    SnsCompressionKSKNoise(TUniformBound),
}

impl NoiseBounds {
    pub fn get_bound(&self) -> TUniformBound {
        match self {
            NoiseBounds::LweNoise(bound) => *bound,
            NoiseBounds::LweHatNoise(bound) => *bound,
            NoiseBounds::GlweNoise(bound) => *bound,
            NoiseBounds::GlweNoiseSnS(bound) => *bound,
            NoiseBounds::CompressionKSKNoise(bound) => *bound,
            NoiseBounds::SnsCompressionKSKNoise(bound) => *bound,
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct NoiseInfo {
    pub amount: usize,
    pub bound: NoiseBounds,
}

impl NoiseInfo {
    pub fn tuniform_bound(&self) -> TUniformBound {
        self.bound.get_bound()
    }

    pub fn num_bits_needed(&self) -> usize {
        self.amount * (self.tuniform_bound().0 + 2)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EncryptionType {
    Bits64,
    Bits128,
}

impl EncryptionType {
    pub fn bit_len(&self) -> usize {
        match self {
            EncryptionType::Bits64 => 64,
            EncryptionType::Bits128 => 128,
        }
    }
}

impl DkgMode {
    pub fn expected_bit_length(&self) -> usize {
        match self {
            DkgMode::Z64 => 64,
            DkgMode::Z128 => 128,
        }
    }
}

#[derive(Debug, PartialEq, Eq)]
pub struct KSKParams {
    pub num_needed_noise: usize,
    pub noise_bound: NoiseBounds,
    pub decomposition_base_log: DecompositionBaseLog,
    pub decomposition_level_count: DecompositionLevelCount,
}

#[derive(Debug)]
pub struct BKParams {
    pub num_needed_noise: usize,
    pub noise_bound: NoiseBounds,
    pub decomposition_base_log: DecompositionBaseLog,
    pub decomposition_level_count: DecompositionLevelCount,
    pub enc_type: EncryptionType,
}

/// Modulus switch noise reduction key parameters
#[derive(Debug)]
pub struct MSNRKParams {
    pub num_needed_noise: usize,
    pub noise_bound: NoiseBounds,
    pub params: ModulusSwitchNoiseReductionParams,
}

#[derive(Debug)]
pub enum MSNRKConfiguration {
    Standard,
    DriftTechniqueNoiseReduction(MSNRKParams),
    CenteredMeanNoiseReduction,
}

#[derive(Debug)]
pub struct DistributedCompressionParameters {
    // For now we only support Classic compression parameters
    // so force the type here
    pub raw_compression_parameters: ClassicCompressionParameters,
    pub ksk_num_noise: usize,
    pub ksk_noisebound: NoiseBounds,
    pub bk_params: BKParams,
    pub pmax: Option<f64>,
}

#[derive(Debug)]
pub struct DistributedSnsCompressionParameters {
    pub raw_compression_parameters: NoiseSquashingCompressionParameters,
    pub ksk_num_noise: usize,
    pub ksk_noisebound: NoiseBounds,
    pub pmax: Option<f64>,
}

// ---------------------------------------------------------------------------
// Basic accessors (read straight out of `meta`).
// ---------------------------------------------------------------------------

impl DKGParams {
    /// The compute parameters as `ClassicPBSParameters`. KMS only supports the
    /// classic PBS atomic pattern; other variants **panic**. Callers must ensure
    /// [`Self::check_conformance`] has passed first (it rejects non-classic
    /// patterns), so this is infallible on validated parameters.
    pub fn classic_pbs(&self) -> ClassicPBSParameters {
        match self.meta.compute_parameters {
            AtomicPatternParameters::Standard(PBSParameters::PBS(p)) => p,
            _ => panic!("KMS only supports the classic PBS atomic pattern"),
        }
    }

    fn dedicated_compact_pk_parameters(&self) -> Option<DedicatedCompactPublicKeyParameters> {
        self.meta.dedicated_compact_public_key_parameters
    }

    /// The raw tfhe-rs regular compression parameters (`None` if compression is
    /// disabled). For the distributed-keygen budget form, see
    /// [`Self::compression_decompression_params`].
    pub fn compression(&self) -> Option<CompressionParameters> {
        self.meta.compression_parameters
    }

    pub fn lwe_dimension(&self) -> LweDimension {
        self.classic_pbs().lwe_dimension
    }

    pub fn glwe_dimension(&self) -> GlweDimension {
        self.classic_pbs().glwe_dimension
    }

    pub fn polynomial_size(&self) -> PolynomialSize {
        self.classic_pbs().polynomial_size
    }

    /// If there is no dedicated CPK, `lwe_hat` is `lwe`.
    pub fn lwe_hat_dimension(&self) -> LweDimension {
        self.dedicated_compact_pk_parameters()
            .map_or(self.lwe_dimension(), |d| {
                d.pke_params.encryption_lwe_dimension
            })
    }

    pub fn glwe_sk_num_bits(&self) -> usize {
        self.polynomial_size().0 * self.glwe_dimension().0
    }

    pub fn lwe_tuniform_bound(&self) -> TUniformBound {
        match self.classic_pbs().lwe_noise_distribution {
            DynamicDistribution::TUniform(n) => TUniformBound(n.bound_log2() as usize),
            _ => panic!("We only support TUniform noise distribution!"),
        }
    }

    pub fn lwe_hat_tuniform_bound(&self) -> TUniformBound {
        self.dedicated_compact_pk_parameters()
            .map_or(self.lwe_tuniform_bound(), |d| {
                match d.pke_params.encryption_noise_distribution {
                    DynamicDistribution::TUniform(n) => TUniformBound(n.bound_log2() as usize),
                    _ => panic!("We only support TUniform noise distribution!"),
                }
            })
    }

    pub fn glwe_tuniform_bound(&self) -> TUniformBound {
        match self.classic_pbs().glwe_noise_distribution {
            DynamicDistribution::TUniform(n) => TUniformBound(n.bound_log2() as usize),
            _ => panic!("We only support TUniform noise distribution!"),
        }
    }

    pub fn decomposition_level_count_ksk(&self) -> DecompositionLevelCount {
        self.classic_pbs().ks_level
    }

    pub fn decomposition_level_count_bk(&self) -> DecompositionLevelCount {
        self.classic_pbs().pbs_level
    }

    pub fn decomposition_level_count_pksk(&self) -> DecompositionLevelCount {
        self.dedicated_compact_pk_parameters()
            .map_or(DecompositionLevelCount(0), |d| d.ksk_params.ks_level)
    }

    pub fn decomposition_level_count_rerand_ksk(&self) -> DecompositionLevelCount {
        self.rerand_params()
            .map_or(DecompositionLevelCount(0), |p| p.ks_level)
    }

    pub fn pksk_destination(&self) -> Option<EncryptionKeyChoice> {
        self.dedicated_compact_pk_parameters()
            .map(|d| d.ksk_params.destination_key)
    }

    pub fn has_dedicated_compact_pk_params(&self) -> bool {
        self.dedicated_compact_pk_parameters().is_some()
    }

    pub fn dedicated_pk_params(
        &self,
    ) -> Option<(
        CompactPublicKeyEncryptionParameters,
        ShortintKeySwitchingParameters,
    )> {
        self.dedicated_compact_pk_parameters()
            .map(|d| (d.pke_params, d.ksk_params))
    }

    pub fn rerand_params(&self) -> Option<ShortintKeySwitchingParameters> {
        self.dedicated_compact_pk_parameters()
            .and_then(|d| d.re_randomization_parameters)
    }

    /// Mirrors `parameters.rs`: the rerand KSK reuses the PKSK (and so needs no
    /// fresh noise) exactly when the two key-switching parameters are equal.
    pub fn rerand_ksk_reuses_pksk(&self) -> bool {
        match (
            self.rerand_params(),
            self.dedicated_pk_params().map(|(_, p)| p),
        ) {
            (Some(rerand), Some(pksk)) => rerand == pksk,
            _ => false,
        }
    }

    pub fn compression_sk_num_bits(&self) -> usize {
        self.compression().map_or(0, |c| {
            c.packing_ks_glwe_dimension().0 * c.packing_ks_polynomial_size().0
        })
    }

    pub fn compression_key_tuniform_bound(&self) -> Option<TUniformBound> {
        if let Some(c) = self.compression() {
            if let DynamicDistribution::TUniform(b) = c.packing_ks_key_noise_distribution() {
                Some(TUniformBound(b.bound_log2() as usize))
            } else {
                panic!("We do not support non-Tuniform noise distribution")
            }
        } else {
            None
        }
    }

    pub fn sk_deviations(&self) -> Option<SecretKeyDeviations> {
        self.secret_key_deviations
    }

    pub fn compact_pk_enc_params(&self) -> CompactPublicKeyEncryptionParameters {
        self.dedicated_compact_pk_parameters().map_or_else(
            || {
                // No dedicated compact public key: derive the CPK encryption
                // parameters from the compute parameters (i.e. no dedicated pk).
                // `TryFrom<PBSParameters> for CompactPublicKeyEncryptionParameters`
                //  can fail in general but only for non-standard atomic patterns, which we reject in `check_conformance()`.
                <ClassicPBSParameters as std::convert::Into<PBSParameters>>::into(
                    self.classic_pbs(),
                )
                .try_into()
                .expect("PBS parameters yield valid CPK encryption parameters")
            },
            |p| p.pke_params,
        )
    }

    /// Validates the KMS-level invariants that
    /// the accessors rely on (classic PBS via [`Self::classic_pbs`],
    /// TUniform noise via the `*_tuniform_bound` helpers, classic compression /
    /// noise-squashing). Call at the parameter-entry boundary so a malformed set
    /// fails fast here rather than panicking deep inside an accessor later.
    pub fn check_conformance(&self) -> anyhow::Result<()> {
        if !self.meta.is_valid() {
            anyhow::bail!("MetaParameters are invalid");
        }

        if self.supports_sns() && self.dkg_mode != DkgMode::Z128 {
            anyhow::bail!("SnS parameters require Z128 dkg_mode");
        }

        // Compute params must be classic PBS with TUniform noise.
        let AtomicPatternParameters::Standard(PBSParameters::PBS(pbs)) =
            self.meta.compute_parameters
        else {
            anyhow::bail!("KMS only supports the classic PBS atomic pattern");
        };
        if !matches!(pbs.lwe_noise_distribution, DynamicDistribution::TUniform(_))
            || !matches!(
                pbs.glwe_noise_distribution,
                DynamicDistribution::TUniform(_)
            )
        {
            anyhow::bail!("KMS only supports the TUniform noise distribution");
        }

        // TODO: KMS currently only supports the legacy re-randomization configuration
        // (`LegacyDedicatedCompactPublicKeyWithKeySwitch`). Lift this restriction once
        // the other `ReRandomizationConfiguration` variants are wired through keygen.
        if let Some(rerand) = self.meta.rerand_configuration.as_ref()
            && !matches!(
                rerand,
                tfhe::shortint::parameters::ReRandomizationConfiguration::LegacyDedicatedCompactPublicKeyWithKeySwitch
            )
        {
            anyhow::bail!(
                "KMS only supports the legacy re-randomization configuration \
                 (LegacyDedicatedCompactPublicKeyWithKeySwitch)"
            );
        }

        // Compression, if present, must be classic with TUniform noise.
        if let Some(compression) = self.meta.compression_parameters {
            let CompressionParameters::Classic(c) = compression else {
                anyhow::bail!("KMS only supports classic compression parameters");
            };
            if !matches!(
                c.packing_ks_key_noise_distribution,
                DynamicDistribution::TUniform(_)
            ) {
                anyhow::bail!("KMS only supports the TUniform noise distribution");
            }
        }

        // Noise squashing, if present, must be classic with TUniform noise
        // (including its optional compression key).
        if let Some(nsp) = self.meta.noise_squashing_parameters {
            let NoiseSquashingParameters::Classic(sns) = nsp.parameters else {
                anyhow::bail!("KMS only supports classic noise-squashing parameters");
            };
            if !matches!(
                sns.glwe_noise_distribution,
                DynamicDistribution::TUniform(_)
            ) {
                anyhow::bail!("KMS only supports the TUniform noise distribution");
            }
            if let Some(sns_comp) = nsp.compression_parameters
                && !matches!(
                    sns_comp.packing_ks_key_noise_distribution,
                    DynamicDistribution::TUniform(_)
                )
            {
                anyhow::bail!("KMS only supports the TUniform noise distribution");
            }
        }

        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Remaining `DKGParamsBasics` accessors ported onto the flattened struct.
// ---------------------------------------------------------------------------

impl DKGParams {
    pub fn dkg_mode(&self) -> DkgMode {
        self.dkg_mode
    }

    pub fn sec(&self) -> u64 {
        self.sec
    }

    pub fn message_modulus(&self) -> MessageModulus {
        self.classic_pbs().message_modulus
    }

    pub fn carry_modulus(&self) -> CarryModulus {
        self.classic_pbs().carry_modulus
    }

    pub fn pmax(&self) -> Option<f64> {
        self.secret_key_deviations.map(|dev| dev.pmax)
    }

    pub fn encryption_key_choice(&self) -> EncryptionKeyChoice {
        self.classic_pbs().encryption_key_choice
    }

    pub fn pbs_order(&self) -> PBSOrder {
        PBSOrder::from(self.encryption_key_choice())
    }

    /// A `temp/dkg/...` path that identifies this parameter set, used **only by
    /// tests** to locate cached key material. The suffix hashes the serialized
    /// parameters, so it is stable across runs for a given set (and more stable
    /// across versions than hashing the `Debug` string would be).
    ///
    /// __Any two parameter sets that share message/carry modulus, SnS presence,
    /// and compression presence and hash identically will collide.__
    #[cfg(any(test, feature = "testing"))]
    pub fn generate_testing_prefix(&self) -> std::path::PathBuf {
        let mut h = std::hash::DefaultHasher::new();
        let serialized = bc2wrap::serialize(self).expect("DKGParams is serializable");
        std::hash::Hash::hash(&serialized, &mut h);
        let hash = std::hash::Hasher::finish(&h);
        std::path::PathBuf::from(format!(
            "temp/dkg/MSGMOD_{}_CARRYMOD_{}_SNS_{}_compression_{}_{}",
            self.message_modulus().0,
            self.carry_modulus().0,
            self.supports_sns(),
            self.compression().is_some(),
            hash
        ))
    }

    pub fn decomposition_base_log_ksk(&self) -> DecompositionBaseLog {
        self.classic_pbs().ks_base_log
    }

    pub fn decomposition_base_log_pksk(&self) -> DecompositionBaseLog {
        self.dedicated_compact_pk_parameters()
            .map_or(DecompositionBaseLog(0), |d| d.ksk_params.ks_base_log)
    }

    pub fn decomposition_base_log_rerand_ksk(&self) -> DecompositionBaseLog {
        self.rerand_params()
            .map_or(DecompositionBaseLog(0), |p| p.ks_base_log)
    }

    pub fn decomposition_base_log_bk(&self) -> DecompositionBaseLog {
        self.classic_pbs().pbs_base_log
    }

    pub fn ksk_params(&self) -> KSKParams {
        let NoiseInfo { amount, bound } = self.num_needed_noise_ksk();
        KSKParams {
            num_needed_noise: amount,
            noise_bound: bound,
            decomposition_base_log: self.decomposition_base_log_ksk(),
            decomposition_level_count: self.decomposition_level_count_ksk(),
        }
    }

    pub fn pksk_params(&self) -> Option<KSKParams> {
        let NoiseInfo { amount, bound } = self.num_needed_noise_pksk();
        self.pksk_destination().map(|_| KSKParams {
            num_needed_noise: amount,
            noise_bound: bound,
            decomposition_base_log: self.decomposition_base_log_pksk(),
            decomposition_level_count: self.decomposition_level_count_pksk(),
        })
    }

    pub fn rerand_ksk_params(&self) -> Option<KSKParams> {
        let NoiseInfo { amount, bound } = self.num_needed_noise_rerand_ksk();
        match self.rerand_params() {
            // Note: Having rerand params without pk parameter would be unusual,
            // but with transciphering we might someday need it.
            Some(rerand) => {
                assert!(
                    matches!(rerand.destination_key, EncryptionKeyChoice::Big),
                    "CompactPublicKey re-randomization can only be enabled \
                    targeting the large secret key."
                );
                Some(KSKParams {
                    num_needed_noise: amount,
                    noise_bound: bound,
                    decomposition_base_log: self.decomposition_base_log_rerand_ksk(),
                    decomposition_level_count: self.decomposition_level_count_rerand_ksk(),
                })
            }
            None => None,
        }
    }

    pub fn bk_params(&self) -> BKParams {
        let NoiseInfo { amount, bound } = self.num_needed_noise_bk();
        BKParams {
            num_needed_noise: amount,
            noise_bound: bound,
            decomposition_base_log: self.decomposition_base_log_bk(),
            decomposition_level_count: self.decomposition_level_count_bk(),
            enc_type: EncryptionType::Bits64,
        }
    }

    pub fn msnrk_configuration(&self) -> MSNRKConfiguration {
        let NoiseInfo { amount, bound } = self.num_needed_noise_msnrk();
        match self.classic_pbs().modulus_switch_noise_reduction_params {
            ModulusSwitchType::Standard => MSNRKConfiguration::Standard,
            ModulusSwitchType::DriftTechniqueNoiseReduction(params) => {
                MSNRKConfiguration::DriftTechniqueNoiseReduction(MSNRKParams {
                    num_needed_noise: amount,
                    noise_bound: bound,
                    params,
                })
            }
            ModulusSwitchType::CenteredMeanNoiseReduction => {
                MSNRKConfiguration::CenteredMeanNoiseReduction
            }
        }
    }

    /// Regular compression parameters in the distributed-keygen form
    /// (`DistributedCompressionParameters`: raw params plus noise/BK budgets).
    /// For the raw tfhe-rs params see [`Self::compression`].
    pub fn compression_decompression_params(&self) -> Option<DistributedCompressionParameters> {
        let comp_params = self.compression()?;
        let CompressionParameters::Classic(classic_comp_params) = comp_params else {
            panic!("We only support classic compression parameters!")
        };
        let NoiseInfo {
            amount: ksk_num_noise,
            bound: ksk_noisebound,
        } = self.num_needed_noise_compression_key();
        let NoiseInfo {
            amount: bk_num_noise,
            bound: bk_noisebound,
        } = self.num_needed_noise_decompression_key();
        let bk_params = BKParams {
            num_needed_noise: bk_num_noise,
            noise_bound: bk_noisebound,
            decomposition_base_log: classic_comp_params.br_base_log,
            decomposition_level_count: classic_comp_params.br_level,
            enc_type: EncryptionType::Bits64,
        };
        Some(DistributedCompressionParameters {
            raw_compression_parameters: classic_comp_params,
            ksk_num_noise,
            ksk_noisebound,
            bk_params,
            pmax: self.pmax(),
        })
    }

    /// SnS compression parameters in the distributed-keygen form
    /// (`DistributedSnsCompressionParameters`). `None` when there is no SnS or
    /// no SnS compression. (The raw `NoiseSquashingCompressionParameters` are
    /// available via `self.sns()?.sns_compression_params()`.)
    pub fn sns_compression_params(&self) -> Option<DistributedSnsCompressionParameters> {
        let sns = self.sns()?;
        let comp_params = sns.sns_compression_params()?;
        let NoiseInfo {
            amount: ksk_num_noise,
            bound: ksk_noisebound,
        } = sns.num_needed_noise_sns_compression_key();
        Some(DistributedSnsCompressionParameters {
            raw_compression_parameters: comp_params,
            ksk_num_noise,
            ksk_noisebound,
            pmax: self.pmax(),
        })
    }

    /// Difference between the output and input bitsize of the pksk.
    pub fn pksk_rshift(&self) -> i8 {
        let nb_bits_input = self
            .dedicated_compact_pk_parameters()
            .map(|d| (d.pke_params.carry_modulus.0 * d.pke_params.carry_modulus.0).ilog2());
        let nb_bits_output = (self.carry_modulus().0 * self.carry_modulus().0).ilog2();
        nb_bits_input
            .map(|nb_bits_input| (nb_bits_output - nb_bits_input) as i8)
            .unwrap_or(0)
    }

    /// Builds the tfhe-rs [`tfhe::Config`] for this parameter set.
    pub fn to_tfhe_config(&self) -> tfhe::Config {
        let pbs_params = self.classic_pbs();
        let compression_params = self.compression_decompression_params();

        let config = tfhe::ConfigBuilder::with_custom_parameters(pbs_params);
        let config = if let Some(dedicated_pk_params) = self.dedicated_pk_params() {
            config.use_dedicated_compact_public_key_parameters(dedicated_pk_params)
        } else {
            config
        };
        let config = if let Some(params) = compression_params {
            config.enable_compression(CompressionParameters::Classic(
                params.raw_compression_parameters,
            ))
        } else {
            config
        };
        let config = if let Some(nsp) = self.meta.noise_squashing_parameters {
            let config = config.enable_noise_squashing(nsp.parameters);
            match nsp.compression_parameters {
                None => config,
                Some(sns_compression_params) => {
                    config.enable_noise_squashing_compression(sns_compression_params)
                }
            }
        } else {
            config
        };
        let config = if let Some(rerand_params) = self.rerand_params() {
            config.enable_ciphertext_re_randomization(rerand_params)
        } else {
            config
        };
        config.build()
    }
}

// ---------------------------------------------------------------------------
// Per-key noise amounts (faithful port of `parameters.rs`).
// ---------------------------------------------------------------------------

impl DKGParams {
    pub fn num_needed_noise_pk(&self) -> NoiseInfo {
        NoiseInfo {
            amount: self.lwe_hat_dimension().0,
            bound: NoiseBounds::LweHatNoise(self.lwe_hat_tuniform_bound()),
        }
    }

    pub fn num_needed_noise_ksk(&self) -> NoiseInfo {
        let amount = self.glwe_dimension().0
            * self.polynomial_size().0
            * self.decomposition_level_count_ksk().0;
        NoiseInfo {
            amount,
            bound: NoiseBounds::LweNoise(self.lwe_tuniform_bound()),
        }
    }

    pub fn num_needed_noise_pksk(&self) -> NoiseInfo {
        let amount = self.lwe_hat_dimension().0 * self.decomposition_level_count_pksk().0;
        // The bound is irrelevant when the amount is 0.
        let (amount, bound) = match self.pksk_destination() {
            Some(EncryptionKeyChoice::Big) => {
                (amount, NoiseBounds::GlweNoise(self.glwe_tuniform_bound()))
            }
            Some(EncryptionKeyChoice::Small) => {
                (amount, NoiseBounds::LweNoise(self.lwe_tuniform_bound()))
            }
            _ => (0, NoiseBounds::LweNoise(self.lwe_tuniform_bound())),
        };
        NoiseInfo { amount, bound }
    }

    pub fn num_needed_noise_rerand_ksk(&self) -> NoiseInfo {
        let amount = if self.rerand_ksk_reuses_pksk() {
            0
        } else {
            self.lwe_hat_dimension().0 * self.decomposition_level_count_rerand_ksk().0
        };
        NoiseInfo {
            amount,
            bound: NoiseBounds::GlweNoise(self.glwe_tuniform_bound()),
        }
    }

    pub fn num_needed_noise_bk(&self) -> NoiseInfo {
        let amount = self.lwe_dimension().0
            * (self.glwe_dimension().0 + 1)
            * self.decomposition_level_count_bk().0
            * self.polynomial_size().0;
        NoiseInfo {
            amount,
            bound: NoiseBounds::GlweNoise(self.glwe_tuniform_bound()),
        }
    }

    pub fn num_needed_noise_msnrk(&self) -> NoiseInfo {
        let amount = match self.classic_pbs().modulus_switch_noise_reduction_params {
            ModulusSwitchType::DriftTechniqueNoiseReduction(p) => p.modulus_switch_zeros_count.0,
            ModulusSwitchType::Standard | ModulusSwitchType::CenteredMeanNoiseReduction => 0,
        };
        NoiseInfo {
            amount,
            bound: NoiseBounds::LweNoise(self.lwe_tuniform_bound()),
        }
    }

    pub fn num_needed_noise_compression_key(&self) -> NoiseInfo {
        match (self.compression(), self.compression_key_tuniform_bound()) {
            (Some(c), Some(bound)) => {
                let amount = self.glwe_dimension().0
                    * self.polynomial_size().0
                    * c.packing_ks_level().0
                    * c.packing_ks_polynomial_size().0;
                NoiseInfo {
                    amount,
                    bound: NoiseBounds::CompressionKSKNoise(bound),
                }
            }
            _ => NoiseInfo {
                amount: 0,
                bound: NoiseBounds::CompressionKSKNoise(TUniformBound::default()),
            },
        }
    }

    pub fn num_needed_noise_decompression_key(&self) -> NoiseInfo {
        match (self.compression(), self.compression_key_tuniform_bound()) {
            (Some(c), Some(_)) => {
                let amount = c.packing_ks_polynomial_size().0
                    * c.packing_ks_glwe_dimension().0
                    * (self.glwe_dimension().0 + 1)
                    * self.polynomial_size().0
                    * c.br_level().0;
                NoiseInfo {
                    amount,
                    bound: NoiseBounds::GlweNoise(self.glwe_tuniform_bound()),
                }
            }
            _ => NoiseInfo {
                amount: 0,
                bound: NoiseBounds::GlweNoise(self.glwe_tuniform_bound()),
            },
        }
    }
}

// ---------------------------------------------------------------------------
// Secret-key bit-sampling counts (faithful port).
// ---------------------------------------------------------------------------

impl DKGParams {
    pub fn lwe_sk_num_bits_to_sample(&self) -> usize {
        let key_size = self.lwe_dimension().0;
        if let Some(dev) = self.secret_key_deviations {
            let prob = compute_prob_hw_within_range(dev.pmax, key_size as u64);
            let tries = compute_min_trials(prob, dev.log2_failure_proba).unwrap();
            tries * key_size
        } else {
            key_size
        }
    }

    pub fn lwe_hat_sk_num_bits_to_sample(&self) -> usize {
        if self.has_dedicated_compact_pk_params() {
            let key_size = self.lwe_hat_dimension().0;
            if let Some(dev) = self.secret_key_deviations {
                let prob = compute_prob_hw_within_range(dev.pmax, key_size as u64);
                let tries = compute_min_trials(prob, dev.log2_failure_proba).unwrap();
                tries * key_size
            } else {
                key_size
            }
        } else {
            0
        }
    }

    pub fn glwe_sk_num_bits_to_sample(&self) -> usize {
        let key_size = self.glwe_sk_num_bits();
        if let Some(dev) = self.secret_key_deviations {
            let individual_key_size = self.polynomial_size().0;
            let log_glwe_dim = (self.glwe_dimension().0.ilog2() + 1) as i64;
            let prob = compute_prob_hw_within_range(dev.pmax, individual_key_size as u64);
            let tries = compute_min_trials(prob, dev.log2_failure_proba - log_glwe_dim).unwrap();
            tries * key_size
        } else {
            key_size
        }
    }

    pub fn compression_sk_num_bits_to_sample(&self) -> usize {
        let key_size = self.compression_sk_num_bits();
        if let (Some(dev), Some(c)) = (self.secret_key_deviations, self.compression()) {
            let individual_key_size = c.packing_ks_polynomial_size().0;
            let log_glwe_dim = (c.packing_ks_glwe_dimension().0.ilog2() + 1) as i64;
            let prob = compute_prob_hw_within_range(dev.pmax, individual_key_size as u64);
            let tries = compute_min_trials(prob, dev.log2_failure_proba - log_glwe_dim).unwrap();
            tries * key_size
        } else {
            key_size
        }
    }
}

// ---------------------------------------------------------------------------
// Aggregate noise + total budgets (faithful port; regular and SnS merged into
// one code path each, branching on `self.sns()`).
// ---------------------------------------------------------------------------

impl DKGParams {
    /// Regular-only raw secret-key bits (excludes SnS). Mirrors
    /// `DKGParamsRegular::num_raw_bits`.
    ///
    /// NOTE: this is intentionally distinct from the SnS contribution. The
    /// legacy code counts the SnS GLWE secret key as *raw* bits in
    /// [`Self::num_raw_bits`] but as *sampled* bits in
    /// [`Self::total_bits_required`]. Conflating the two (building
    /// `total_bits_required` on top of `num_raw_bits`) double-counts the SnS
    /// GLWE key, so `total_bits_required` must build on this regular-only base.
    fn regular_num_raw_bits(&self, keyset_config: KeySetConfig) -> usize {
        match keyset_config {
            KeySetConfig::Standard(config) => match config.secret_key_config {
                KeyGenSecretKeyConfig::GenerateAll => {
                    self.lwe_sk_num_bits_to_sample()
                        + self.lwe_hat_sk_num_bits_to_sample()
                        + self.lwe_sk_num_bits_to_sample() // second sk is for oprf
                        + self.glwe_sk_num_bits_to_sample()
                        + self.compression_sk_num_bits_to_sample()
                }
                KeyGenSecretKeyConfig::UseExisting => self.lwe_sk_num_bits_to_sample(),
            },
            KeySetConfig::DecompressionOnly => 0,
        }
    }

    pub fn num_raw_bits(&self, keyset_config: KeySetConfig) -> usize {
        let mut bits = self.regular_num_raw_bits(keyset_config);

        // ⚠️ DISCLAIMER — BEHAVIOR CHANGE vs the legacy `parameters_old.rs`.
        //
        // The legacy `DKGParamsSnS::num_raw_bits` added the *raw* SnS key sizes
        // (`glwe_sk_num_bits_sns`, `sns_compression_sk_num_bits`), even though it
        // counts every *regular* key with rejection-sampling overhead
        // (`*_to_sample`) and `total_bits_required` counts the SnS keys with that
        // overhead as well. For SnS parameter sets that carry
        // `secret_key_deviations` (e.g. the NIST sets) this made `num_raw_bits`
        // inconsistent with both the regular keys and `total_bits_required`, and
        // broke the intended invariant
        //   `total_bits_required == num_raw_bits + Σ(noise bits)`.
        //
        // Here we use the `*_to_sample` variants so the SnS keys are accounted
        // exactly like the regular ones, restoring that invariant. This is
        // INTENTIONALLY DIFFERENT from the legacy result for SnS params with
        // `secret_key_deviations`; for every other parameter set the value is
        // unchanged (without deviations, raw == to_sample).
        if let (Some(sns), KeySetConfig::Standard(_)) = (self.sns(), keyset_config) {
            bits +=
                sns.glwe_sk_num_bits_sns_to_sample() + sns.sns_compression_sk_num_bits_to_sample();
        }
        bits
    }

    /// Regular-only total bits (regular raw bits + regular noise). Mirrors
    /// `DKGParamsRegular::total_bits_required`.
    fn regular_total_bits_required(&self, keyset_config: KeySetConfig) -> usize {
        let mut n = self.regular_num_raw_bits(keyset_config);

        match keyset_config {
            KeySetConfig::Standard(_) => {
                n += self.num_needed_noise_pk().num_bits_needed();
                n += self.num_needed_noise_ksk().num_bits_needed();
                n += self.num_needed_noise_bk().num_bits_needed();
                n += self.num_needed_noise_bk().num_bits_needed(); // dedicated OPRF bk
                n += self.num_needed_noise_pksk().num_bits_needed();
                n += self.num_needed_noise_compression_key().num_bits_needed();
                n += self.num_needed_noise_msnrk().num_bits_needed();
                n += self.num_needed_noise_decompression_key().num_bits_needed();
                n += self.num_needed_noise_rerand_ksk().num_bits_needed();
            }
            KeySetConfig::DecompressionOnly => {
                n += self.num_needed_noise_decompression_key().num_bits_needed();
            }
        }
        n
    }

    pub fn total_bits_required(&self, keyset_config: KeySetConfig) -> usize {
        // Build on the regular-only base (NOT `num_raw_bits`) — see
        // `regular_num_raw_bits`. The SnS GLWE key enters here as *sampled*
        // bits, matching `DKGParamsSnS::total_bits_required`.
        let mut n = self.regular_total_bits_required(keyset_config);

        if let (Some(sns), KeySetConfig::Standard(_)) = (self.sns(), keyset_config) {
            n += sns.glwe_sk_num_bits_sns_to_sample();
            n += sns.all_bk_sns_noise().num_bits_needed();
            n += sns.num_needed_noise_msnrk_sns().num_bits_needed();
            n += sns.num_needed_noise_sns_compression_key().num_bits_needed();
            n += sns.sns_compression_sk_num_bits_to_sample();
        }
        n
    }

    pub fn total_triples_required(&self, keyset_config: KeySetConfig) -> usize {
        // Compression BK triples are needed in both Standard and DecompressionOnly.
        let compression_bk_triples = self.compression().map_or(0, |c| {
            self.glwe_sk_num_bits()
                * (c.packing_ks_glwe_dimension().0 * c.packing_ks_polynomial_size().0)
        });

        let mut triples = match keyset_config {
            KeySetConfig::Standard(_) => match self.sns() {
                // regular BK + OPRF BK + SnS BK
                Some(sns) => {
                    self.lwe_dimension().0
                        * (2 * self.glwe_sk_num_bits() + sns.glwe_sk_num_bits_sns())
                }
                // regular BK + OPRF BK
                None => 2 * self.lwe_dimension().0 * self.glwe_sk_num_bits(),
            },
            KeySetConfig::DecompressionOnly => 0,
        };
        triples += compression_bk_triples;

        self.total_bits_required(keyset_config) + triples
    }

    pub fn total_randomness_required(&self, keyset_config: KeySetConfig) -> usize {
        // One extra element to sample the seed (we always work in huge rings).
        self.total_bits_required(keyset_config) + 1
    }

    pub fn all_lwe_noise(&self, keyset_config: KeySetConfig) -> NoiseInfo {
        match keyset_config {
            KeySetConfig::Standard(_) => {
                let target_bound = self.num_needed_noise_ksk().bound;
                let regular = combine_noise_info(
                    target_bound,
                    &[
                        self.num_needed_noise_ksk(),
                        self.num_needed_noise_pksk(),
                        self.num_needed_noise_msnrk(),
                    ],
                );
                match self.sns() {
                    Some(sns) => combine_noise_info(
                        regular.bound,
                        &[regular, sns.num_needed_noise_msnrk_sns()],
                    ),
                    None => regular,
                }
            }
            KeySetConfig::DecompressionOnly => NoiseInfo {
                amount: 0,
                bound: NoiseBounds::LweNoise(self.lwe_tuniform_bound()),
            },
        }
    }

    pub fn all_lwe_hat_noise(&self, keyset_config: KeySetConfig) -> NoiseInfo {
        match keyset_config {
            KeySetConfig::Standard(_) => self.num_needed_noise_pk(),
            KeySetConfig::DecompressionOnly => NoiseInfo {
                amount: 0,
                bound: NoiseBounds::LweHatNoise(self.lwe_hat_tuniform_bound()),
            },
        }
    }

    pub fn all_glwe_noise(&self, keyset_config: KeySetConfig) -> NoiseInfo {
        let target_bound = self.num_needed_noise_bk().bound;
        match keyset_config {
            KeySetConfig::Standard(_) => combine_noise_info(
                target_bound,
                &[
                    self.num_needed_noise_bk(), // regular bk
                    self.num_needed_noise_bk(), // oprf bk
                    self.num_needed_noise_pksk(),
                    self.num_needed_noise_decompression_key(),
                    self.num_needed_noise_rerand_ksk(),
                ],
            ),
            KeySetConfig::DecompressionOnly => {
                combine_noise_info(target_bound, &[self.num_needed_noise_decompression_key()])
            }
        }
    }

    pub fn all_compression_ksk_noise(&self, keyset_config: KeySetConfig) -> NoiseInfo {
        match keyset_config {
            KeySetConfig::Standard(_) => self.num_needed_noise_compression_key(),
            KeySetConfig::DecompressionOnly => NoiseInfo {
                amount: 0,
                bound: NoiseBounds::CompressionKSKNoise(TUniformBound::default()),
            },
        }
    }
}

// ---------------------------------------------------------------------------
// SnS view: SnS-only accessors, obtained once via `DKGParams::sns()`.
// ---------------------------------------------------------------------------

/// Borrowed view over the SnS parameters of a [`DKGParams`]. Only obtainable
/// when noise squashing is present, so every method here is infallible.
#[derive(Clone, Copy)]
pub struct SnsView<'a> {
    params: &'a DKGParams,
    sns_params: NoiseSquashingParameters,
    sns_compression_params: Option<NoiseSquashingCompressionParameters>,
}

impl DKGParams {
    /// Returns an [`SnsView`] iff this parameter set has noise squashing.
    pub fn sns(&self) -> Option<SnsView<'_>> {
        self.meta.noise_squashing_parameters.map(|nsp| SnsView {
            params: self,
            sns_params: nsp.parameters,
            sns_compression_params: nsp.compression_parameters,
        })
    }

    /// Whether this parameter set carries noise-squashing (SnS) parameters.
    pub fn supports_sns(&self) -> bool {
        self.meta.noise_squashing_parameters.is_some()
    }
}

impl SnsView<'_> {
    /// The raw tfhe-rs noise-squashing parameters.
    pub fn sns_params(&self) -> NoiseSquashingParameters {
        self.sns_params
    }

    /// The raw tfhe-rs SnS compression parameters. For the distributed-keygen
    /// form see [`DKGParams::sns_compression_params`].
    pub fn sns_compression_params(&self) -> Option<NoiseSquashingCompressionParameters> {
        self.sns_compression_params
    }

    pub fn polynomial_size_sns(&self) -> PolynomialSize {
        self.sns_params.polynomial_size()
    }

    pub fn glwe_dimension_sns(&self) -> GlweDimension {
        self.sns_params.glwe_dimension()
    }

    pub fn glwe_tuniform_bound_sns(&self) -> TUniformBound {
        match self.sns_params.glwe_noise_distribution() {
            DynamicDistribution::TUniform(t) => TUniformBound(t.bound_log2() as usize),
            DynamicDistribution::Gaussian(_) => panic!("we only support tuniform!"),
        }
    }

    pub fn decomposition_level_count_bk_sns(&self) -> DecompositionLevelCount {
        self.sns_params.decomp_level_count()
    }

    pub fn decomposition_base_log_bk_sns(&self) -> DecompositionBaseLog {
        self.sns_params.decomp_base_log()
    }

    pub fn glwe_sk_num_bits_sns(&self) -> usize {
        self.polynomial_size_sns().0 * self.glwe_dimension_sns().0
    }

    pub fn glwe_sk_num_bits_sns_to_sample(&self) -> usize {
        let key_size = self.glwe_sk_num_bits_sns();
        if let Some(dev) = self.params.secret_key_deviations {
            let individual_key_size = self.polynomial_size_sns().0;
            let log_glwe_dim = (self.glwe_dimension_sns().0.ilog2() + 1) as i64;
            let prob = compute_prob_hw_within_range(dev.pmax, individual_key_size as u64);
            let tries = compute_min_trials(prob, dev.log2_failure_proba - log_glwe_dim).unwrap();
            tries * key_size
        } else {
            key_size
        }
    }

    pub fn all_bk_sns_noise(&self) -> NoiseInfo {
        let amount = self.params.lwe_dimension().0
            * (self.glwe_dimension_sns().0 + 1)
            * self.decomposition_level_count_bk_sns().0
            * self.polynomial_size_sns().0;
        NoiseInfo {
            amount,
            bound: NoiseBounds::GlweNoiseSnS(self.glwe_tuniform_bound_sns()),
        }
    }

    pub fn bk_sns_params(&self) -> BKParams {
        let NoiseInfo {
            amount: num_needed_noise,
            bound: noise_bound,
        } = self.all_bk_sns_noise();
        BKParams {
            num_needed_noise,
            noise_bound,
            decomposition_base_log: self.decomposition_base_log_bk_sns(),
            decomposition_level_count: self.decomposition_level_count_bk_sns(),
            enc_type: EncryptionType::Bits128,
        }
    }

    fn classic_sns_params(&self) -> NoiseSquashingClassicParameters {
        match self.sns_params {
            NoiseSquashingParameters::Classic(c) => c,
            NoiseSquashingParameters::MultiBit(_) => {
                panic!("We do not support multi bit SnS params yet")
            }
        }
    }

    pub fn num_needed_noise_msnrk_sns(&self) -> NoiseInfo {
        let classic = self.classic_sns_params();
        let amount = match classic.modulus_switch_noise_reduction_params {
            ModulusSwitchType::DriftTechniqueNoiseReduction(p) => p.modulus_switch_zeros_count.0,
            ModulusSwitchType::Standard | ModulusSwitchType::CenteredMeanNoiseReduction => 0,
        };
        NoiseInfo {
            amount,
            bound: NoiseBounds::LweNoise(self.params.lwe_tuniform_bound()),
        }
    }

    pub fn msnrk_configuration_sns(&self) -> MSNRKConfiguration {
        let classic_sns_params = self.classic_sns_params();
        let NoiseInfo { amount, bound } = self.num_needed_noise_msnrk_sns();
        match classic_sns_params.modulus_switch_noise_reduction_params {
            ModulusSwitchType::Standard => MSNRKConfiguration::Standard,
            ModulusSwitchType::DriftTechniqueNoiseReduction(params) => {
                MSNRKConfiguration::DriftTechniqueNoiseReduction(MSNRKParams {
                    num_needed_noise: amount,
                    noise_bound: bound,
                    params,
                })
            }
            ModulusSwitchType::CenteredMeanNoiseReduction => {
                MSNRKConfiguration::CenteredMeanNoiseReduction
            }
        }
    }

    pub fn sns_compression_sk_num_bits(&self) -> usize {
        match self.sns_compression_params {
            Some(p) => p.packing_ks_polynomial_size.0 * p.packing_ks_glwe_dimension.0,
            None => 0,
        }
    }

    fn sns_compression_key_tuniform_bound(&self) -> Option<TUniformBound> {
        if let Some(p) = self.sns_compression_params {
            if let DynamicDistribution::TUniform(b) = p.packing_ks_key_noise_distribution {
                Some(TUniformBound(b.bound_log2() as usize))
            } else {
                panic!("We do not support non-Tuniform noise distribution")
            }
        } else {
            None
        }
    }

    pub fn num_needed_noise_sns_compression_key(&self) -> NoiseInfo {
        match (
            self.sns_compression_params,
            self.sns_compression_key_tuniform_bound(),
        ) {
            (Some(comp), Some(bound)) => {
                let amount = self.sns_params.glwe_dimension().0
                    * self.sns_params.polynomial_size().0
                    * comp.packing_ks_level.0
                    * comp.packing_ks_polynomial_size.0;
                NoiseInfo {
                    amount,
                    bound: NoiseBounds::SnsCompressionKSKNoise(bound),
                }
            }
            _ => NoiseInfo {
                amount: 0,
                bound: NoiseBounds::SnsCompressionKSKNoise(TUniformBound::default()),
            },
        }
    }

    pub fn sns_compression_sk_num_bits_to_sample(&self) -> usize {
        if self.sns_compression_params.is_none() {
            return 0;
        }
        let key_size = self.sns_compression_sk_num_bits();
        if let Some(dev) = self.params.secret_key_deviations {
            let (individual_key_size, log_glwe_dim) = match self.sns_compression_params {
                Some(p) => (
                    p.packing_ks_polynomial_size.0,
                    (p.packing_ks_glwe_dimension.0.ilog2() + 1) as i64,
                ),
                None => (0, 0),
            };
            let prob = compute_prob_hw_within_range(dev.pmax, individual_key_size as u64);
            let tries = compute_min_trials(prob, dev.log2_failure_proba - log_glwe_dim).unwrap();
            tries * key_size
        } else {
            key_size
        }
    }
}

/// Computes the probability that the Hamming weight of a binary string is within
/// [(1-pmax)*size; pmax*size]
// `pub(crate)` so `parameters_new.rs` reuses the identical sampling-trial math.
pub(crate) fn compute_prob_hw_within_range(pmax: f64, size: u64) -> f64 {
    assert!(pmax > 0.5 && pmax < 1.0);
    let distribution = Binomial::new(0.5, size).unwrap();
    let (min_hw, max_hw) = compute_min_max_hw(pmax, size);
    distribution.cdf(max_hw) - distribution.cdf(min_hw)
}

/// Computes the minimum number of trials k needed to achieve at least one success
/// with probability >=1-p_failure, where each trial has success probability p.
///
/// Formula: k >= log_p_failure/log2(1 - p)
pub(crate) fn compute_min_trials(p: f64, log2_p_failure: i64) -> Result<usize, String> {
    // Input validation
    if p <= 0.0 {
        return Err(format!("p={} must be in the range (0, 1].", p));
    }

    // If each trial is guaranteed to succeed, only one trial is needed
    if p == 1.0 {
        return Ok(1);
    }

    let one_minus_p = 1.0 - p;

    let k_float = (log2_p_failure as f64) / one_minus_p.log2();

    // Round up to get the minimum integer number of trials
    let k = k_float.ceil() as usize;

    Ok(k)
}

pub(crate) fn compute_min_max_hw(pmax: f64, size: u64) -> (u64, u64) {
    assert!(pmax > 0.5 && pmax < 1.0);
    let max_hw = (pmax * size as f64).floor() as u64;
    let min_hw = ((1.0 - pmax) * size as f64).floor() as u64;
    (min_hw, max_hw)
}

pub(crate) fn combine_noise_info(target_bound: NoiseBounds, list: &[NoiseInfo]) -> NoiseInfo {
    let mut total = 0;
    for noise_info in list {
        match (noise_info.bound, target_bound) {
            (NoiseBounds::LweNoise(_left), NoiseBounds::LweNoise(_right)) => {
                total += noise_info.amount;
                #[cfg(test)]
                assert_eq!(_left.0, _right.0);
            }
            (NoiseBounds::LweHatNoise(_left), NoiseBounds::LweHatNoise(_right)) => {
                total += noise_info.amount;
                #[cfg(test)]
                assert_eq!(_left.0, _right.0);
            }
            (NoiseBounds::GlweNoise(_left), NoiseBounds::GlweNoise(_right)) => {
                total += noise_info.amount;
                #[cfg(test)]
                assert_eq!(_left.0, _right.0);
            }
            (NoiseBounds::GlweNoiseSnS(_left), NoiseBounds::GlweNoiseSnS(_right)) => {
                total += noise_info.amount;
                #[cfg(test)]
                assert_eq!(_left.0, _right.0);
            }
            (NoiseBounds::CompressionKSKNoise(_left), NoiseBounds::CompressionKSKNoise(_right)) => {
                total += noise_info.amount;
                #[cfg(test)]
                assert_eq!(_left.0, _right.0);
            }
            _ => { /* do nothing */ }
        }
    }
    NoiseInfo {
        amount: total,
        bound: target_bound,
    }
}

#[cfg_attr(test, derive(strum::EnumIter))]
#[derive(ValueEnum, Clone, Debug)]
#[allow(non_camel_case_types)]
pub enum DkgParamsAvailable {
    NIST_PARAMS_P32_NO_SNS_FGLWE,
    NIST_PARAMS_P32_SNS_FGLWE,
    NIST_PARAMS_P8_NO_SNS_FGLWE,
    NIST_PARAMS_P8_SNS_FGLWE,
    NIST_PARAMS_P32_NO_SNS_LWE,
    NIST_PARAMS_P32_SNS_LWE,
    NIST_PARAMS_P8_NO_SNS_LWE,
    NIST_PARAMS_P8_SNS_LWE,
    BC_PARAMS_NO_SNS,
    BC_PARAMS_SNS,
    BC_PARAMS_NIGEL_NO_SNS,
    BC_PARAMS_NIGEL_SNS,
    PARAMS_TEST_BK_SNS,
}

impl DkgParamsAvailable {
    /// Maps a CLI-selected parameter set to its flattened [`DKGParams`].
    pub fn to_param(&self) -> DKGParams {
        match self {
            DkgParamsAvailable::NIST_PARAMS_P32_NO_SNS_FGLWE => *NIST_PARAMS_P32_NO_SNS_FGLWE,
            DkgParamsAvailable::NIST_PARAMS_P32_SNS_FGLWE => NIST_PARAMS_P32_SNS_FGLWE,
            DkgParamsAvailable::NIST_PARAMS_P8_NO_SNS_FGLWE => *NIST_PARAMS_P8_NO_SNS_FGLWE,
            DkgParamsAvailable::NIST_PARAMS_P8_SNS_FGLWE => NIST_PARAMS_P8_SNS_FGLWE,
            DkgParamsAvailable::NIST_PARAMS_P32_NO_SNS_LWE => *NIST_PARAMS_P32_NO_SNS_LWE,
            DkgParamsAvailable::NIST_PARAMS_P32_SNS_LWE => NIST_PARAMS_P32_SNS_LWE,
            DkgParamsAvailable::NIST_PARAMS_P8_NO_SNS_LWE => *NIST_PARAMS_P8_NO_SNS_LWE,
            DkgParamsAvailable::NIST_PARAMS_P8_SNS_LWE => NIST_PARAMS_P8_SNS_LWE,
            DkgParamsAvailable::BC_PARAMS_NO_SNS => *BC_PARAMS_NO_SNS,
            DkgParamsAvailable::BC_PARAMS_SNS => BC_PARAMS_SNS,
            DkgParamsAvailable::BC_PARAMS_NIGEL_NO_SNS => *BC_PARAMS_NIGEL_NO_SNS,
            DkgParamsAvailable::BC_PARAMS_NIGEL_SNS => BC_PARAMS_NIGEL_SNS,
            DkgParamsAvailable::PARAMS_TEST_BK_SNS => PARAMS_TEST_BK_SNS,
        }
    }
}

/// Production parameters. Selectable over the gRPC API via `FheParameter::Default`.
pub const BC_PARAMS_SNS: DKGParams = DKGParams {
    dkg_mode: DkgMode::Z128,
    sec: 128,
    meta: MetaParameters {
        backend: Backend::Cpu,
        compute_parameters: AtomicPatternParameters::Standard(PBSParameters::PBS(tfhe::shortint::parameters::current_params::V1_6_PARAM_MESSAGE_2_CARRY_2_KS_PBS_TUNIFORM_2M128)),
        dedicated_compact_public_key_parameters: Some(DedicatedCompactPublicKeyParameters { pke_params: tfhe::shortint::parameters::current_params::V1_6_PARAM_PKE_MESSAGE_2_CARRY_2_KS_PBS_TUNIFORM_2M128, ksk_params:  tfhe::shortint::parameters::current_params::V1_6_PARAM_KEYSWITCH_MESSAGE_2_CARRY_2_KS_PBS_TUNIFORM_2M128, re_randomization_parameters: Some(tfhe::shortint::parameters::current_params::V1_6_PARAM_KEYSWITCH_PKE_TO_BIG_MESSAGE_2_CARRY_2_KS_PBS_TUNIFORM_2M128) }),
        compression_parameters: Some(tfhe::shortint::parameters::current_params::V1_6_COMP_PARAM_MESSAGE_2_CARRY_2_KS_PBS_TUNIFORM_2M128),
        noise_squashing_parameters: Some(MetaNoiseSquashingParameters{ parameters: tfhe::shortint::parameters::current_params::V1_6_NOISE_SQUASHING_PARAM_MESSAGE_2_CARRY_2_KS_PBS_TUNIFORM_2M128, compression_parameters: Some(tfhe::shortint::parameters::current_params::V1_6_NOISE_SQUASHING_COMP_PARAM_MESSAGE_2_CARRY_2_KS_PBS_TUNIFORM_2M128) }),
        rerand_configuration: Some(tfhe::shortint::parameters::ReRandomizationConfiguration::LegacyDedicatedCompactPublicKeyWithKeySwitch),
    },
    secret_key_deviations: None,
};

// ---------------------------------------------------------------------------
// The remaining SnS parameter sets, translated from `parameters_old` into the
// flattened `DKGParams`. Each one is pinned to `DKGParams::from(<legacy const>)`
// by the `new_consts_match_from_old` test below.
// ---------------------------------------------------------------------------

/// Benchmark-only parameters: not reachable over the gRPC `FheParameter` enum (used by the experiments CLI and tests).
pub const BC_PARAMS_NIGEL_SNS: DKGParams = DKGParams {
    dkg_mode: DkgMode::Z128,
    sec: 128,
    meta: MetaParameters {
        backend: Backend::Cpu,
        compute_parameters: AtomicPatternParameters::Standard(PBSParameters::PBS(
            ClassicPBSParameters {
                lwe_dimension: LweDimension(928),
                glwe_dimension: GlweDimension(1),
                polynomial_size: PolynomialSize(2048),
                lwe_noise_distribution: DynamicDistribution::new_t_uniform(44),
                glwe_noise_distribution: DynamicDistribution::new_t_uniform(16),
                pbs_base_log: DecompositionBaseLog(21),
                pbs_level: DecompositionLevelCount(1),
                ks_base_log: DecompositionBaseLog(5),
                ks_level: DecompositionLevelCount(3),
                message_modulus: MessageModulus(4),
                carry_modulus: CarryModulus(4),
                max_noise_level: MaxNoiseLevel::new(5),
                log2_p_fail: -64.0629,
                ciphertext_modulus: CiphertextModulus::new_native(),
                encryption_key_choice: EncryptionKeyChoice::Big,
                modulus_switch_noise_reduction_params: ModulusSwitchType::CenteredMeanNoiseReduction,
            },
        )),
        dedicated_compact_public_key_parameters: Some(DedicatedCompactPublicKeyParameters {
            pke_params: CompactPublicKeyEncryptionParameters {
                encryption_lwe_dimension: LweDimension(1024),
                encryption_noise_distribution: DynamicDistribution::new_t_uniform(42),
                message_modulus: MessageModulus(4),
                carry_modulus: CarryModulus(4),
                ciphertext_modulus: CiphertextModulus::new_native(),
                expansion_kind: CompactCiphertextListExpansionKind::RequiresCasting,
                zk_scheme: SupportedCompactPkeZkScheme::V1,
            },
            ksk_params: ShortintKeySwitchingParameters {
                ks_level: DecompositionLevelCount(1),
                ks_base_log: DecompositionBaseLog(17),
                destination_key: EncryptionKeyChoice::Big,
            },
            re_randomization_parameters: Some(ShortintKeySwitchingParameters {
                ks_level: DecompositionLevelCount(1),
                ks_base_log: DecompositionBaseLog(17),
                destination_key: EncryptionKeyChoice::Big,
            }),
        }),
        compression_parameters: None,
        noise_squashing_parameters: Some(MetaNoiseSquashingParameters {
            parameters: NoiseSquashingParameters::Classic(NoiseSquashingClassicParameters {
                glwe_dimension: GlweDimension(2),
                glwe_noise_distribution: DynamicDistribution::new_t_uniform(27),
                polynomial_size: PolynomialSize(2048),
                decomp_base_log: DecompositionBaseLog(24),
                decomp_level_count: DecompositionLevelCount(3),
                ciphertext_modulus: CiphertextModulus::<u128>::new_native(),
                modulus_switch_noise_reduction_params: ModulusSwitchType::CenteredMeanNoiseReduction,
                message_modulus: MessageModulus(4),
                carry_modulus: CarryModulus(4),
            }),
            compression_parameters: None,
        }),
        rerand_configuration: Some(
            tfhe::shortint::parameters::ReRandomizationConfiguration::LegacyDedicatedCompactPublicKeyWithKeySwitch,
        ),
    },
    secret_key_deviations: None,
};

/// Test-production parameters (small, deliberately insecure). Selectable over the gRPC API via `FheParameter::Test`.
pub const PARAMS_TEST_BK_SNS: DKGParams = DKGParams {
    // SnS ⇒ Z128 (the legacy regular params were Z64, coerced by `from_regular`).
    dkg_mode: DkgMode::Z128,
    sec: 128,
    meta: MetaParameters {
        backend: Backend::Cpu,
        compute_parameters: AtomicPatternParameters::Standard(PBSParameters::PBS(
            ClassicPBSParameters {
                lwe_dimension: LweDimension(1),
                glwe_dimension: GlweDimension(1),
                polynomial_size: PolynomialSize(256),
                lwe_noise_distribution: DynamicDistribution::new_t_uniform(0),
                glwe_noise_distribution: DynamicDistribution::new_t_uniform(0),
                pbs_base_log: DecompositionBaseLog(24),
                pbs_level: DecompositionLevelCount(1),
                ks_base_log: DecompositionBaseLog(37),
                ks_level: DecompositionLevelCount(1),
                message_modulus: MessageModulus(4),
                carry_modulus: CarryModulus(4),
                max_noise_level: MaxNoiseLevel::new(5),
                log2_p_fail: -64f64,
                ciphertext_modulus: CiphertextModulus::new_native(),
                encryption_key_choice: EncryptionKeyChoice::Big,
                modulus_switch_noise_reduction_params:
                    ModulusSwitchType::DriftTechniqueNoiseReduction(
                        ModulusSwitchNoiseReductionParams {
                            modulus_switch_zeros_count: LweCiphertextCount(10),
                            ms_bound: NoiseEstimationMeasureBound(288230376151711744f64),
                            ms_r_sigma_factor: RSigmaFactor(9.75539320076416),
                            ms_input_variance: Variance(1.92631390716519e-10),
                        },
                    ),
            },
        )),
        dedicated_compact_public_key_parameters: Some(DedicatedCompactPublicKeyParameters {
            pke_params: CompactPublicKeyEncryptionParameters {
                encryption_lwe_dimension: LweDimension(512),
                encryption_noise_distribution: DynamicDistribution::new_t_uniform(0),
                message_modulus: MessageModulus(4),
                carry_modulus: CarryModulus(4),
                ciphertext_modulus: CiphertextModulus::new_native(),
                expansion_kind: CompactCiphertextListExpansionKind::RequiresCasting,
                zk_scheme: SupportedCompactPkeZkScheme::V2,
            },
            ksk_params: ShortintKeySwitchingParameters {
                ks_level: DecompositionLevelCount(1),
                ks_base_log: DecompositionBaseLog(37),
                destination_key: EncryptionKeyChoice::Small,
            },
            re_randomization_parameters: Some(ShortintKeySwitchingParameters {
                ks_level: DecompositionLevelCount(1),
                ks_base_log: DecompositionBaseLog(17),
                destination_key: EncryptionKeyChoice::Big,
            }),
        }),
        compression_parameters: Some(CompressionParameters::Classic(ClassicCompressionParameters {
            br_level: DecompositionLevelCount(1),
            br_base_log: DecompositionBaseLog(24),
            packing_ks_level: DecompositionLevelCount(1),
            packing_ks_base_log: DecompositionBaseLog(27),
            packing_ks_polynomial_size: PolynomialSize(256),
            packing_ks_glwe_dimension: GlweDimension(1),
            lwe_per_glwe: LweCiphertextCount(256),
            storage_log_modulus: tfhe::core_crypto::prelude::CiphertextModulusLog(9),
            packing_ks_key_noise_distribution: DynamicDistribution::new_t_uniform(0),
        })),
        noise_squashing_parameters: Some(MetaNoiseSquashingParameters {
            parameters: NoiseSquashingParameters::Classic(NoiseSquashingClassicParameters {
                glwe_dimension: GlweDimension(1),
                glwe_noise_distribution: DynamicDistribution::new_t_uniform(0),
                polynomial_size: PolynomialSize(256),
                decomp_base_log: DecompositionBaseLog(33),
                decomp_level_count: DecompositionLevelCount(2),
                ciphertext_modulus: CiphertextModulus::<u128>::new_native(),
                modulus_switch_noise_reduction_params:
                    ModulusSwitchType::DriftTechniqueNoiseReduction(
                        ModulusSwitchNoiseReductionParams {
                            modulus_switch_zeros_count: LweCiphertextCount(8),
                            ms_bound: NoiseEstimationMeasureBound(288230376151711744f64),
                            ms_r_sigma_factor: RSigmaFactor(9.2),
                            ms_input_variance: Variance(2.182718682903484e-224),
                        },
                    ),
                message_modulus: MessageModulus(4),
                carry_modulus: CarryModulus(4),
            }),
            compression_parameters: Some(NoiseSquashingCompressionParameters {
                packing_ks_level: DecompositionLevelCount(1),
                packing_ks_base_log: DecompositionBaseLog(61),
                packing_ks_polynomial_size: PolynomialSize(256),
                packing_ks_glwe_dimension: GlweDimension(1),
                lwe_per_glwe: LweCiphertextCount(128),
                packing_ks_key_noise_distribution: DynamicDistribution::new_t_uniform(3),
                ciphertext_modulus: CiphertextModulus::<u128>::new_native(),
                message_modulus: MessageModulus(4),
                carry_modulus: CarryModulus(4),
            }),
        }),
        rerand_configuration: Some(
            tfhe::shortint::parameters::ReRandomizationConfiguration::LegacyDedicatedCompactPublicKeyWithKeySwitch,
        ),
    },
    secret_key_deviations: None,
};

/// Benchmark-only parameters: not reachable over the gRPC `FheParameter` enum (used by the experiments CLI and tests).
pub const NIST_PARAMS_P8_SNS_LWE: DKGParams = DKGParams {
    dkg_mode: DkgMode::Z128,
    sec: 128,
    meta: MetaParameters {
        backend: Backend::Cpu,
        compute_parameters: AtomicPatternParameters::Standard(PBSParameters::PBS(
            super::raw_parameters::NIST_PARAM_1_CARRY_1_COMPACT_PK_PBS_KS_TUNIFORM_2M128,
        )),
        dedicated_compact_public_key_parameters: Some(DedicatedCompactPublicKeyParameters {
            pke_params: super::raw_parameters::NIST_PARAM_PKE_MESSAGE_1_CARRY_1_PBS_KS_TUNIFORM_2M128,
            ksk_params:
                super::raw_parameters::NIST_PARAM_KEYSWITCH_PKE_MESSAGE_1_CARRY_1_PBS_KS_TUNIFORM_2M128,
            re_randomization_parameters: None,
        }),
        compression_parameters: None,
        noise_squashing_parameters: Some(MetaNoiseSquashingParameters {
            parameters:
                super::raw_parameters::NIST_PARAMS_NOISE_SQUASHING_MESSAGE_1_CARRY_1_PBS_KS_TUNIFORM_2M128,
            compression_parameters: None,
        }),
        rerand_configuration: None,
    },
    secret_key_deviations: Some(SecretKeyDeviations {
        log2_failure_proba: -80,
        pmax: 0.798,
    }),
};

/// Benchmark-only parameters: not reachable over the gRPC `FheParameter` enum (used by the experiments CLI and tests).
pub const NIST_PARAMS_P32_SNS_LWE: DKGParams = DKGParams {
    dkg_mode: DkgMode::Z128,
    sec: 128,
    meta: MetaParameters {
        backend: Backend::Cpu,
        compute_parameters: AtomicPatternParameters::Standard(PBSParameters::PBS(
            super::raw_parameters::NIST_PARAM_2_CARRY_2_COMPACT_PK_PBS_KS_TUNIFORM_2M128,
        )),
        dedicated_compact_public_key_parameters: Some(DedicatedCompactPublicKeyParameters {
            pke_params: super::raw_parameters::NIST_PARAM_PKE_MESSAGE_2_CARRY_2_PBS_KS_TUNIFORM_2M128,
            ksk_params:
                super::raw_parameters::NIST_PARAM_KEYSWITCH_PKE_MESSAGE_2_CARRY_2_PBS_KS_TUNIFORM_2M128,
            re_randomization_parameters: None,
        }),
        compression_parameters: None,
        noise_squashing_parameters: Some(MetaNoiseSquashingParameters {
            parameters:
                super::raw_parameters::NIST_PARAMS_NOISE_SQUASHING_MESSAGE_2_CARRY_2_PBS_KS_TUNIFORM_2M128,
            compression_parameters: None,
        }),
        rerand_configuration: None,
    },
    secret_key_deviations: Some(SecretKeyDeviations {
        log2_failure_proba: -80,
        pmax: 0.8044,
    }),
};

/// Benchmark-only parameters: not reachable over the gRPC `FheParameter` enum (used by the experiments CLI and tests).
pub const NIST_PARAMS_P8_SNS_FGLWE: DKGParams = DKGParams {
    dkg_mode: DkgMode::Z128,
    sec: 128,
    meta: MetaParameters {
        backend: Backend::Cpu,
        compute_parameters: AtomicPatternParameters::Standard(PBSParameters::PBS(
            super::raw_parameters::NIST_PARAM_1_CARRY_1_COMPACT_PK_KS_PBS_TUNIFORM_2M128,
        )),
        dedicated_compact_public_key_parameters: Some(DedicatedCompactPublicKeyParameters {
            pke_params: super::raw_parameters::NIST_PARAM_PKE_MESSAGE_1_CARRY_1_KS_PBS_TUNIFORM_2M128,
            ksk_params:
                super::raw_parameters::NIST_PARAM_KEYSWITCH_PKE_MESSAGE_1_CARRY_1_KS_PBS_TUNIFORM_2M128,
            re_randomization_parameters: Some(
                super::raw_parameters::NIST_PARAM_KEYSWITCH_PKE_MESSAGE_1_CARRY_1_KS_PBS_TUNIFORM_2M128,
            ),
        }),
        compression_parameters: None,
        noise_squashing_parameters: Some(MetaNoiseSquashingParameters {
            parameters:
                super::raw_parameters::NIST_PARAMS_NOISE_SQUASHING_MESSAGE_1_CARRY_1_KS_PBS_TUNIFORM_2M128,
            compression_parameters: None,
        }),
        rerand_configuration: Some(
            tfhe::shortint::parameters::ReRandomizationConfiguration::LegacyDedicatedCompactPublicKeyWithKeySwitch,
        ),
    },
    secret_key_deviations: Some(SecretKeyDeviations {
        log2_failure_proba: -80,
        pmax: 0.5022,
    }),
};

/// Benchmark-only parameters: not reachable over the gRPC `FheParameter` enum (used by the experiments CLI and tests).
pub const NIST_PARAMS_P32_SNS_FGLWE: DKGParams = DKGParams {
    dkg_mode: DkgMode::Z128,
    sec: 128,
    meta: MetaParameters {
        backend: Backend::Cpu,
        compute_parameters: AtomicPatternParameters::Standard(PBSParameters::PBS(
            super::raw_parameters::NIST_PARAM_2_CARRY_2_COMPACT_PK_KS_PBS_TUNIFORM_2M128,
        )),
        dedicated_compact_public_key_parameters: Some(DedicatedCompactPublicKeyParameters {
            pke_params: super::raw_parameters::NIST_PARAM_PKE_MESSAGE_2_CARRY_2_KS_PBS_TUNIFORM_2M128,
            ksk_params:
                super::raw_parameters::NIST_PARAM_KEYSWITCH_PKE_MESSAGE_2_CARRY_2_KS_PBS_TUNIFORM_2M128,
            re_randomization_parameters: Some(
                super::raw_parameters::NIST_PARAM_KEYSWITCH_PKE_MESSAGE_2_CARRY_2_KS_PBS_TUNIFORM_2M128,
            ),
        }),
        compression_parameters: None,
        noise_squashing_parameters: Some(MetaNoiseSquashingParameters {
            parameters:
                super::raw_parameters::NIST_PARAMS_NOISE_SQUASHING_MESSAGE_2_CARRY_2_KS_PBS_TUNIFORM_2M128,
            compression_parameters: None,
        }),
        rerand_configuration: Some(
            tfhe::shortint::parameters::ReRandomizationConfiguration::LegacyDedicatedCompactPublicKeyWithKeySwitch,
        ),
    },
    secret_key_deviations: Some(SecretKeyDeviations {
        log2_failure_proba: -80,
        pmax: 0.7499,
    }),
};

impl DKGParams {
    /// Returns a copy of these parameters with the noise-squashing (SnS) part
    /// removed, yielding the corresponding non-SnS parameter set. Everything
    /// else (compute params, dedicated CPK, compression, rerand, dkg_mode,
    /// secret-key deviations) is preserved.
    pub fn remove_sns_parameters(&self) -> Self {
        let mut stripped = *self;
        stripped.meta.noise_squashing_parameters = None;
        stripped
    }
}

// Non-SnS counterparts, derived by stripping the SnS part off the SnS sets.
// (PARAMS_TEST_BK has no non-SnS counterpart in the legacy params.)
/// Benchmark-only parameters: not reachable over the gRPC `FheParameter` enum (used by the experiments CLI and tests).
pub static BC_PARAMS_NO_SNS: LazyLock<DKGParams> =
    LazyLock::new(|| BC_PARAMS_SNS.remove_sns_parameters());
/// Benchmark-only parameters: not reachable over the gRPC `FheParameter` enum (used by the experiments CLI and tests).
pub static BC_PARAMS_NIGEL_NO_SNS: LazyLock<DKGParams> =
    LazyLock::new(|| BC_PARAMS_NIGEL_SNS.remove_sns_parameters());
/// Benchmark-only parameters: not reachable over the gRPC `FheParameter` enum (used by the experiments CLI and tests).
pub static NIST_PARAMS_P8_NO_SNS_LWE: LazyLock<DKGParams> =
    LazyLock::new(|| NIST_PARAMS_P8_SNS_LWE.remove_sns_parameters());
/// Benchmark-only parameters: not reachable over the gRPC `FheParameter` enum (used by the experiments CLI and tests).
pub static NIST_PARAMS_P32_NO_SNS_LWE: LazyLock<DKGParams> =
    LazyLock::new(|| NIST_PARAMS_P32_SNS_LWE.remove_sns_parameters());
/// Benchmark-only parameters: not reachable over the gRPC `FheParameter` enum (used by the experiments CLI and tests).
pub static NIST_PARAMS_P8_NO_SNS_FGLWE: LazyLock<DKGParams> =
    LazyLock::new(|| NIST_PARAMS_P8_SNS_FGLWE.remove_sns_parameters());
/// Benchmark-only parameters: not reachable over the gRPC `FheParameter` enum (used by the experiments CLI and tests).
pub static NIST_PARAMS_P32_NO_SNS_FGLWE: LazyLock<DKGParams> =
    LazyLock::new(|| NIST_PARAMS_P32_SNS_FGLWE.remove_sns_parameters());

// ---------------------------------------------------------------------------
// Equivalence test: every budget/noise/sample count must match the legacy
// `DKGParams` implementation for every shipped parameter set.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::keyset_config::{KeySetConfig, StandardKeySetConfig};
    use crate::tfhe_internals::parameters_old::DKGParamsOld;
    use strum::IntoEnumIterator;

    // `KeySetConfig` does not implement `Debug`, so we carry an explicit label
    // for assertion messages.
    fn all_keyset_configs() -> Vec<(KeySetConfig, &'static str)> {
        vec![
            (
                KeySetConfig::Standard(StandardKeySetConfig::default()),
                "Standard(GenerateAll)",
            ),
            (
                KeySetConfig::Standard(StandardKeySetConfig::use_existing_sk()),
                "Standard(UseExisting)",
            ),
            (KeySetConfig::DecompressionOnly, "DecompressionOnly"),
        ]
    }

    /// Independently sums the noise bits that `total_bits_required` folds in, so
    /// the invariant test below cross-checks `num_raw_bits` against
    /// `total_bits_required` without re-deriving the raw-key accounting.
    fn expected_noise_bits(p: &DKGParams, keyset_config: KeySetConfig) -> usize {
        match keyset_config {
            KeySetConfig::DecompressionOnly => {
                p.num_needed_noise_decompression_key().num_bits_needed()
            }
            KeySetConfig::Standard(_) => {
                let mut n = p.num_needed_noise_pk().num_bits_needed()
                    + p.num_needed_noise_ksk().num_bits_needed()
                    + p.num_needed_noise_bk().num_bits_needed()
                    + p.num_needed_noise_bk().num_bits_needed() // dedicated OPRF bk
                    + p.num_needed_noise_pksk().num_bits_needed()
                    + p.num_needed_noise_compression_key().num_bits_needed()
                    + p.num_needed_noise_msnrk().num_bits_needed()
                    + p.num_needed_noise_decompression_key().num_bits_needed()
                    + p.num_needed_noise_rerand_ksk().num_bits_needed();
                if let Some(sns) = p.sns() {
                    n += sns.all_bk_sns_noise().num_bits_needed()
                        + sns.num_needed_noise_msnrk_sns().num_bits_needed()
                        + sns.num_needed_noise_sns_compression_key().num_bits_needed();
                }
                n
            }
        }
    }

    /// Regression test for a `num_raw_bits` accounting bug: the invariant
    /// `total_bits_required == num_raw_bits + Σ(noise bits)` must hold. An earlier
    /// `num_raw_bits` counted the SnS keys as raw bits (no rejection-sampling
    /// overhead) while `total_bits_required` counted them with overhead, which
    /// broke this invariant for SnS parameter sets carrying `secret_key_deviations`
    /// (the NIST sets). The two accounting paths must stay consistent.
    #[test]
    fn regression_num_raw_bits_total_bits_invariant() {
        for variant in DkgParamsAvailable::iter() {
            let p = variant.to_param();
            for (keyset_config, label) in all_keyset_configs() {
                assert_eq!(
                    p.total_bits_required(keyset_config),
                    p.num_raw_bits(keyset_config) + expected_noise_bits(&p, keyset_config),
                    "total_bits_required != num_raw_bits + noise for {variant:?} / {label}"
                );
            }
        }
    }

    /// `check_conformance` accepts every shipped parameter set and rejects the
    /// SnS-implies-Z128 invariant violation.
    #[test]
    fn check_conformance_accepts_shipped_rejects_sns_z64() {
        for variant in DkgParamsAvailable::iter() {
            let p = variant.to_param();
            p.check_conformance()
                .unwrap_or_else(|e| panic!("{variant:?} should be conformant: {e}"));
        }
        // SnS parameters require Z128; forcing Z64 must be rejected.
        let mut bad = PARAMS_TEST_BK_SNS;
        bad.dkg_mode = DkgMode::Z64;
        assert!(
            bad.check_conformance().is_err(),
            "SnS parameters with Z64 dkg_mode must be rejected"
        );
    }

    /// Asserts that the flattened `DKGParams` produces byte-for-byte the same
    /// triples / bits / randomness / noise budgets as the legacy `DKGParams`,
    /// for every constant in `DkgParamsAvailable` and every `KeySetConfig`.
    /// Pins each hand-written `*` constant (and each `*_NO_SNS` derived
    /// via `remove_sns_parameters`) to the authoritative `DKGParams::from(<legacy>)`
    /// translation, so any transcription error in the literals fails here with a
    /// precise diff rather than silently shipping wrong parameters.
    #[test]
    fn new_consts_match_from_old() {
        use crate::tfhe_internals::parameters_old as old;
        // SnS sets (const literals)
        assert_eq!(
            BC_PARAMS_SNS,
            DKGParams::from(old::BC_PARAMS_SNS_OLD),
            "BC_PARAMS_SNS"
        );
        assert_eq!(
            BC_PARAMS_NIGEL_SNS,
            DKGParams::from(old::BC_PARAMS_NIGEL_SNS_OLD),
            "BC_PARAMS_NIGEL_SNS"
        );
        assert_eq!(
            PARAMS_TEST_BK_SNS,
            DKGParams::from(old::PARAMS_TEST_BK_SNS_OLD),
            "PARAMS_TEST_BK_SNS"
        );
        assert_eq!(
            NIST_PARAMS_P8_SNS_LWE,
            DKGParams::from(old::NIST_PARAMS_P8_SNS_LWE_OLD),
            "NIST_PARAMS_P8_SNS_LWE"
        );
        assert_eq!(
            NIST_PARAMS_P32_SNS_LWE,
            DKGParams::from(old::NIST_PARAMS_P32_SNS_LWE_OLD),
            "NIST_PARAMS_P32_SNS_LWE"
        );
        assert_eq!(
            NIST_PARAMS_P8_SNS_FGLWE,
            DKGParams::from(old::NIST_PARAMS_P8_SNS_FGLWE_OLD),
            "NIST_PARAMS_P8_SNS_FGLWE"
        );
        assert_eq!(
            NIST_PARAMS_P32_SNS_FGLWE,
            DKGParams::from(old::NIST_PARAMS_P32_SNS_FGLWE_OLD),
            "NIST_PARAMS_P32_SNS_FGLWE"
        );
        // non-SnS sets (derived via remove_sns_parameters)
        assert_eq!(
            *BC_PARAMS_NO_SNS,
            DKGParams::from(old::BC_PARAMS_NO_SNS_OLD),
            "BC_PARAMS_NO_SNS"
        );
        assert_eq!(
            *BC_PARAMS_NIGEL_NO_SNS,
            DKGParams::from(old::BC_PARAMS_NIGEL_NO_SNS_OLD),
            "BC_PARAMS_NIGEL_NO_SNS"
        );
        assert_eq!(
            *NIST_PARAMS_P8_NO_SNS_LWE,
            DKGParams::from(old::NIST_PARAMS_P8_NO_SNS_LWE_OLD),
            "NIST_PARAMS_P8_NO_SNS_LWE"
        );
        assert_eq!(
            *NIST_PARAMS_P32_NO_SNS_LWE,
            DKGParams::from(old::NIST_PARAMS_P32_NO_SNS_LWE_OLD),
            "NIST_PARAMS_P32_NO_SNS_LWE"
        );
        assert_eq!(
            *NIST_PARAMS_P8_NO_SNS_FGLWE,
            DKGParams::from(old::NIST_PARAMS_P8_NO_SNS_FGLWE_OLD),
            "NIST_PARAMS_P8_NO_SNS_FGLWE"
        );
        assert_eq!(
            *NIST_PARAMS_P32_NO_SNS_FGLWE,
            DKGParams::from(old::NIST_PARAMS_P32_NO_SNS_FGLWE_OLD),
            "NIST_PARAMS_P32_NO_SNS_FGLWE"
        );
    }

    #[test]
    fn budgets_match_legacy_for_all_params() {
        for variant in DkgParamsAvailable::iter() {
            let old: DKGParamsOld = variant.to_old_version();
            let new = DKGParams::from(old);
            let h = old.get_params_basics_handle();
            let label = format!("{variant:?}");

            // ---- config-dependent totals + aggregate noise ----
            for (ksc, ksc_label) in all_keyset_configs() {
                // `num_raw_bits` INTENTIONALLY diverges from legacy for SnS
                // params with `secret_key_deviations` (see the disclaimer on
                // `DKGParams::num_raw_bits`): the SnS keys are now counted
                // with sampling overhead (`*_to_sample`), exactly like the
                // regular keys. The expected new value is the legacy value plus
                // the raw->to_sample correction for the SnS keys (which is 0
                // when the params carry no deviations, i.e. raw == to_sample).
                let legacy_raw = h.num_raw_bits(ksc);
                let expected_raw = if let (Some(sns), KeySetConfig::Standard(_)) = (new.sns(), ksc)
                {
                    legacy_raw
                        + (sns.glwe_sk_num_bits_sns_to_sample() - sns.glwe_sk_num_bits_sns())
                        + (sns.sns_compression_sk_num_bits_to_sample()
                            - sns.sns_compression_sk_num_bits())
                } else {
                    legacy_raw
                };
                assert_eq!(
                    new.num_raw_bits(ksc),
                    expected_raw,
                    "num_raw_bits for {label} / {ksc_label}"
                );

                // The fix restores the intended invariant for ALL params (it was
                // broken for SnS-with-deviations under the legacy code):
                //   total_bits_required == num_raw_bits + Σ(noise bits)
                // where the noise productions are exactly those the DKG
                // orchestrator splits out (`all_*_noise` + the SnS noises;
                // `msnrk_sns` is already folded into `all_lwe_noise`).
                if let KeySetConfig::Standard(_) = ksc {
                    let mut noise_bits = new.all_lwe_noise(ksc).num_bits_needed()
                        + new.all_glwe_noise(ksc).num_bits_needed()
                        + new.all_compression_ksk_noise(ksc).num_bits_needed()
                        + new.all_lwe_hat_noise(ksc).num_bits_needed();
                    if let Some(sns) = new.sns() {
                        noise_bits += sns.all_bk_sns_noise().num_bits_needed()
                            + sns.num_needed_noise_sns_compression_key().num_bits_needed();
                    }
                    assert_eq!(
                        new.total_bits_required(ksc),
                        new.num_raw_bits(ksc) + noise_bits,
                        "invariant total_bits == num_raw_bits + noise for {label} / {ksc_label}"
                    );
                }

                assert_eq!(
                    new.total_bits_required(ksc),
                    h.total_bits_required(ksc),
                    "total_bits_required mismatch for {label} / {ksc_label}"
                );
                assert_eq!(
                    new.total_triples_required(ksc),
                    h.total_triples_required(ksc),
                    "total_triples_required mismatch for {label} / {ksc_label}"
                );
                assert_eq!(
                    new.total_randomness_required(ksc),
                    h.total_randomness_required(ksc),
                    "total_randomness_required mismatch for {label} / {ksc_label}"
                );

                let aggregate = [
                    (
                        new.all_lwe_noise(ksc),
                        h.all_lwe_noise(ksc),
                        "all_lwe_noise",
                    ),
                    (
                        new.all_lwe_hat_noise(ksc),
                        h.all_lwe_hat_noise(ksc),
                        "all_lwe_hat_noise",
                    ),
                    (
                        new.all_glwe_noise(ksc),
                        h.all_glwe_noise(ksc),
                        "all_glwe_noise",
                    ),
                    (
                        new.all_compression_ksk_noise(ksc),
                        h.all_compression_ksk_noise(ksc),
                        "all_compression_ksk_noise",
                    ),
                ];
                for (got, exp, name) in aggregate {
                    assert_eq!(
                        got.amount, exp.amount,
                        "{name}.amount for {label} / {ksc_label}"
                    );
                    assert_eq!(
                        got.num_bits_needed(),
                        exp.num_bits_needed(),
                        "{name}.num_bits_needed for {label} / {ksc_label}"
                    );
                }
            }

            // ---- config-independent per-key noise ----
            let per_key = [
                (new.num_needed_noise_pk(), h.num_needed_noise_pk(), "pk"),
                (new.num_needed_noise_ksk(), h.num_needed_noise_ksk(), "ksk"),
                (
                    new.num_needed_noise_pksk(),
                    h.num_needed_noise_pksk(),
                    "pksk",
                ),
                (new.num_needed_noise_bk(), h.num_needed_noise_bk(), "bk"),
                (
                    new.num_needed_noise_compression_key(),
                    h.num_needed_noise_compression_key(),
                    "compression_key",
                ),
                (
                    new.num_needed_noise_decompression_key(),
                    h.num_needed_noise_decompression_key(),
                    "decompression_key",
                ),
                (
                    new.num_needed_noise_rerand_ksk(),
                    h.num_needed_noise_rerand_ksk(),
                    "rerand_ksk",
                ),
                (
                    new.num_needed_noise_msnrk(),
                    h.num_needed_noise_msnrk(),
                    "msnrk",
                ),
            ];
            for (got, exp, name) in per_key {
                assert_eq!(
                    got.amount, exp.amount,
                    "num_needed_noise_{name}.amount for {label}"
                );
                assert_eq!(
                    got.num_bits_needed(),
                    exp.num_bits_needed(),
                    "num_needed_noise_{name}.num_bits_needed for {label}"
                );
            }

            // ---- secret-key sampling counts ----
            assert_eq!(
                new.lwe_sk_num_bits_to_sample(),
                h.lwe_sk_num_bits_to_sample(),
                "lwe_sk_num_bits_to_sample for {label}"
            );
            assert_eq!(
                new.lwe_hat_sk_num_bits_to_sample(),
                h.lwe_hat_sk_num_bits_to_sample(),
                "lwe_hat_sk_num_bits_to_sample for {label}"
            );
            assert_eq!(
                new.glwe_sk_num_bits_to_sample(),
                h.glwe_sk_num_bits_to_sample(),
                "glwe_sk_num_bits_to_sample for {label}"
            );
            assert_eq!(
                new.compression_sk_num_bits_to_sample(),
                h.compression_sk_num_bits_to_sample(),
                "compression_sk_num_bits_to_sample for {label}"
            );

            // ---- SnS-specific budget pieces ----
            if let DKGParamsOld::WithSnS(old_sns) = old {
                let sns = new.sns().expect("flattened params must expose an SnS view");
                assert_eq!(
                    sns.glwe_sk_num_bits_sns(),
                    old_sns.glwe_sk_num_bits_sns(),
                    "glwe_sk_num_bits_sns for {label}"
                );
                assert_eq!(
                    sns.glwe_sk_num_bits_sns_to_sample(),
                    old_sns.glwe_sk_num_bits_sns_to_sample(),
                    "glwe_sk_num_bits_sns_to_sample for {label}"
                );
                assert_eq!(
                    sns.sns_compression_sk_num_bits(),
                    old_sns.sns_compression_sk_num_bits(),
                    "sns_compression_sk_num_bits for {label}"
                );
                assert_eq!(
                    sns.sns_compression_sk_num_bits_to_sample(),
                    old_sns.sns_compression_sk_num_bits_to_sample(),
                    "sns_compression_sk_num_bits_to_sample for {label}"
                );

                let (a, b) = (sns.all_bk_sns_noise(), old_sns.all_bk_sns_noise());
                assert_eq!(a.amount, b.amount, "all_bk_sns_noise.amount for {label}");
                assert_eq!(
                    a.num_bits_needed(),
                    b.num_bits_needed(),
                    "all_bk_sns_noise.num_bits_needed for {label}"
                );

                let (a, b) = (
                    sns.num_needed_noise_sns_compression_key(),
                    old_sns.num_needed_noise_sns_compression_key(),
                );
                assert_eq!(
                    a.amount, b.amount,
                    "num_needed_noise_sns_compression_key.amount for {label}"
                );
                assert_eq!(
                    a.num_bits_needed(),
                    b.num_bits_needed(),
                    "num_needed_noise_sns_compression_key.num_bits_needed for {label}"
                );
            } else {
                assert!(
                    !new.supports_sns(),
                    "WithoutSnS must map to no SnS view for {label}"
                );
            }

            // Every shipped parameter set must pass conformance.
            new.check_conformance()
                .unwrap_or_else(|e| panic!("check_conformance failed for {label}: {e}"));
        }
    }
}
