# Actionlint.yaml config file is automatically detected by cilint.yaml job
# and contains the label of zama runners
self-hosted-runner:
  labels:
    - large_ubuntu_16_arm
    - large_ubuntu_32
    - runs-on=github.run_id/runner=16cpu-linux-x64/spot=true