rules:
  use-trusted-publishing:
    ignore:
      # ignore line 61 in workflow-pr-dockerfile.yml, any column
      - workflow-pr-dockerfile.yml:61
  secrets-inherit:
    ignore:
      - performance-testing.yml:223