version: v2beta1
name: kmsgit

vars:
  RUST_IMAGE_VERSION: "$(cat toolchain.txt)"

# localRegistry:
#   enabled: true
#   localbuild: true


# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  build:
    run: |-
      build_images core-service core-client -t latest-fegm   # 3. Build, tag (git commit hash) and push core-service image (see "images")
  deploy:
    run: |-
      # --- pre-deploy hook (add your commands here) ---
      echo "Connecting to the cluster"
      vcluster connect kms-for-developers
      # --- end pre-deploy hook ---

      run_dependencies --all                                  # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all                               # 2. Ensure pull secrets
      build_images --all -t latest-fegm   # 3. Build, tag (git commit hash) and push core-service image (see "images")
      create_deployments --all                                # 4. Deploy Helm charts and manifests specfied as "deployments"

# This is a list of `images` that DevSpace can build for this project
# We recommend to skip image building during development (devspace dev) as much as possible
images:
  rust-golden-image:
    image: ghcr.io/zama-ai/kms/rust-golden-image:latest
    tags:
      - latest-dev
    createPullSecret: true
    dockerfile: ./docker/base/Dockerfile
    context: .
    buildArgs:
      RUST_IMAGE_VERSION: "${RUST_IMAGE_VERSION}"
  core-service:
    image: hub.zama.org/dev-kms/core-service
    tags:
      - latest-fegm
    createPullSecret: true
    dockerfile: ./docker/core/service/Dockerfile
    context: .
    rebuildStrategy: ignoreContextChanges
    kaniko:
      initImage: "public.ecr.aws/docker/library/alpine:latest"
      image: cgr.dev/zama.ai/kaniko:v1.25.5
      resources:
        requests:
          memory: "64Gi"
          cpu: "32"
        limits:
          memory: "64Gi"
          cpu: "32"
      cache: true
      args:
        - "--custom-platform=linux/amd64"
        - "--cache-run-layers=true"
        - "--cache-copy-layers=true"
      tolerations:
        - key: karpenter.sh/nodepool
          operator: Equal
          value: kms-vcluster-pool
          effect: NoSchedule
    buildArgs:
      RUST_IMAGE_VERSION: "${RUST_IMAGE_VERSION}"


  core-client:
    image: hub.zama.org/dev-kms/core-client
    tags:
      - latest-fegm
    dockerfile: ./docker/core-client/Dockerfile
    context: .
    rebuildStrategy: ignoreContextChanges
    kaniko:
      initImage: "public.ecr.aws/docker/library/alpine:latest"
      image: cgr.dev/zama.ai/kaniko:v1.25.5
      resources:
        requests:
          memory: "64Gi"
          cpu: "32"
        limits:
          memory: "64Gi"
          cpu: "32"
      cache: true
      args:
        - "--custom-platform=linux/amd64"
        - "--cache-run-layers=true"
        - "--cache-copy-layers=true"
      tolerations:
        - key: karpenter.sh/nodepool
          operator: Equal
          value: kms-vcluster-pool
          effect: NoSchedule
    buildArgs:
      RUST_IMAGE_VERSION: "${RUST_IMAGE_VERSION}"

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  localstack:
    helm:
      releaseName: localstack
      chart:
        name: localstack-charts
        repo: https://localstack.github.io/helm-charts
      valuesFiles:
        - "./ci/kube-testing/infra/localstack-s3-vcluster-values.yaml"
  kms-core-1:
    helm:
      releaseName: kms-service-threshold-1-kms-test
      chart:
        name: ./charts/kms-core
      values:
        kmsPeers.id: "1"
        kmsCore.image.name: ghcr.io/zama-ai/kms/core-service
        kmsCore.image.tag: latest-dev
        kmsCoreClient.image.name: ghcr.io/zama-ai/kms/core-client
        kmsCoreClient.image.tag: latest-dev
      valuesFiles:
        - "./ci/kube-testing/kms/values-kms-test-vcluster.yaml"
  kms-core-2:
    helm:
      releaseName: kms-service-threshold-2-kms-test
      chart:
        name: ./charts/kms-core
      values:
        kmsPeers.id: "2"
        kmsCore.image.name: ghcr.io/zama-ai/kms/core-service
        kmsCore.image.tag: latest-dev
        kmsCoreClient.image.name: ghcr.io/zama-ai/kms/core-client
        kmsCoreClient.image.tag: latest-dev
      valuesFiles:
        - "./ci/kube-testing/kms/values-kms-test-vcluster.yaml"
  kms-core-3:
    helm:
      releaseName: kms-service-threshold-3-kms-test
      chart:
        name: ./charts/kms-core
      values:
        kmsPeers.id: "3"
        kmsCore.image.name: ghcr.io/zama-ai/kms/core-service
        kmsCore.image.tag: latest-dev
        kmsCoreClient.image.name: ghcr.io/zama-ai/kms/core-client
        kmsCoreClient.image.tag: latest-dev
      valuesFiles:
          - "./ci/kube-testing/kms/values-kms-test-vcluster.yaml"
  kms-core-4:
    helm:
      releaseName: kms-service-threshold-4-kms-test
      chart:
        name: ./charts/kms-core
      values:
        kmsPeers.id: "4"
        kmsCore.image.name: ghcr.io/zama-ai/kms/core-service
        kmsCore.image.tag: latest-dev
        kmsCoreClient.image.name: ghcr.io/zama-ai/kms/core-client
        kmsCoreClient.image.tag: latest-dev
      valuesFiles:
        - "./ci/kube-testing/kms/values-kms-test-vcluster.yaml"
  kms-core-init:
    helm:
      releaseName: kms-core-init
      chart:
        name: ./charts/kms-core
      values:
        kmsCore.image.name: ghcr.io/zama-ai/kms/core-service
        kmsCore.image.tag: latest-dev
        kmsCoreClient.image.name: ghcr.io/zama-ai/kms/core-client
        kmsCoreClient.image.tag: latest-dev
      valuesFiles:
        - "./ci/kube-testing/kms/values-kms-service-init-kms-test-vcluster.yaml"
# This is a list of `dev` containers that are based on the containers created by your deployments
# dev:
#   app:
#     # Search for the container that runs this image
#     imageSelector: ghcr.io/zama-ai/kms/core-service:latest
#     # Replace the container image with this dev-optimized image (allows to skip image building during development)
#     devImage: ghcr.io/loft-sh/devspace-containers/rust:1.67-alpine
#     # Sync files between the local filesystem and the development container
#     sync:
#       - path: ./
#         uploadExcludeFile: .dockerignore
#     # Open a terminal and use the following command to start it
#     terminal:
#       command: ./devspace_start.sh
#     # Inject a lightweight SSH server into the container (so your IDE can connect to the remote dev env)
#     ssh:
#       enabled: true
#     # Make the following commands from my local machine available inside the dev container
#     proxyCommands:
#       - command: devspace
#       - command: kubectl
#       - command: helm
#       - gitCredentials: true
#     # Forward the following ports to be able access your application via localhost
#     ports:
#       - port: "50100"
#     # Open the following URLs once they return an HTTP status code other than 502 or 503
#     open:
#       - url: http://localhost:50100

# # Use the `commands` section to define repeatable dev workflows for this project
# commands:
#   migrate-db:
#     command: |-
#       echo 'This is a cross-platform, shared command that can be used to codify any kind of dev task.'
#       echo 'Anyone using this project can invoke it via "devspace run migrate-db"'

# Define dependencies to other projects with a devspace.yaml
# dependencies:
#   api:
#     git: https://...  # Git-based dependencies
#     tag: v1.0.0
#   ui:
#     path: ./ui        # Path-based dependencies (for monorepos)
