version: v2beta1
name: kmsgit

vars:
  NAMESPACE:
    question: "Enter the namespace for the KMS deployment \n  Namespace must be a valid Kubernetes namespace like kms-test-<username> with \"-\" instead of \"_\"\n"
  TKMS_INFRA_CHART_VERSION: 0.3.2
  TAG_NAME:
    question: "Enter the tag name for the KMS deployment (e.g. latest-fegm)"
    default: "latest-vcluster"
  RUST_IMAGE_VERSION: "$(cat toolchain.txt)"
  PCR0:
    command: |-
      docker pull --platform=linux/amd64 ghcr.io/zama-ai/kms/core-service-enclave:"${TAG_NAME}"
      docker inspect ghcr.io/zama-ai/kms/core-service-enclave:"${TAG_NAME}" | jq -r '.[0].Config.Labels["zama.kms.eif_pcr0"]'
  PCR1:
    command: |-
      docker pull --platform=linux/amd64 ghcr.io/zama-ai/kms/core-service-enclave:"${TAG_NAME}"
      docker inspect ghcr.io/zama-ai/kms/core-service-enclave:"${TAG_NAME}" | jq -r '.[0].Config.Labels["zama.kms.eif_pcr1"]'
  PCR2:
    command: |-
      docker pull --platform=linux/amd64 ghcr.io/zama-ai/kms/core-service-enclave:"${TAG_NAME}"
      docker inspect ghcr.io/zama-ai/kms/core-service-enclave:"${TAG_NAME}" | jq -r '.[0].Config.Labels["zama.kms.eif_pcr2"]'
pullSecrets:
  cgr:
    registry: "cgr.dev"
    secret: "cgr-registry-credentials"
    serviceAccounts:
      - default
  ghcr:
    registry: "ghcr.io"
    secret: "ghcr-registry-credentials"
    serviceAccounts:
      - default
  hub:
    registry: "hub.zama.org"
    secret: "registry-credentials"
    serviceAccounts:
      - default

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  build:
    run: |-
      ensure_pull_secrets --all
      build_images core-client core-service -t ${TAG_NAME}
  deploy: |-
      ensure_pull_secrets --all
      echo ${DEVSPACE_NAMESPACE}
      run_pipelines deploy-infra
      # run_pipelines deploy-kms
      # run_pipelines deploy-kms-init
  deploy-infra: |-
      echo "PCR0=${PCR0}"
      echo "PCR1=${PCR1}"
      echo "PCR2=${PCR2}"
      create_deployments tkms-infra
  deploy-kms: |-
      ensure_pull_secrets --all
      wait_pod --label-selector="crossplane.io/claim-name=kms-party-${DEVSPACE_NAMESPACE}" --namespace "${NAMESPACE}"
      create_deployments kms-core-1 kms-core-2 kms-core-3 kms-core-4
  deploy-kms-init: |-
      wait_pod --label-selector="crossplane.io/claim-name=kms-party-${DEVSPACE_NAMESPACE}" --namespace "${NAMESPACE}"
      ensure_pull_secrets --all
      create_deployments kms-core-init
  dev: |-
    run_pipelines build
    run_pipelines deploy
  port-forward: |-
    start_dev --all

# This is a list of `images` that DevSpace can build for this project
# We recommend to skip image building during development (devspace dev) as much as possible
# images:
#   core-service:
#     image: hub.zama.org/dev-kms/core-service
#     tags:
#       - ${TAG_NAME}
#     dockerfile: ./docker/core/service/Dockerfile
#     context: .
#     rebuildStrategy: ignoreContextChanges
#     createPullSecret: false
#     kaniko:
#       initImage: "public.ecr.aws/docker/library/alpine:latest"
#       pullSecret: registry-credentials
#       resources:
#         requests:
#           memory: "128Gi"
#           cpu: "64"
#         limits:
#           memory: "128Gi"
#           cpu: "64"
#       cache: true
#       args:
#         - "--custom-platform=linux/amd64"
#         - "--cache-run-layers=true"
#         - "--cache-copy-layers=true"
#       tolerations:
#         - key: karpenter.sh/nodepool
#           operator: Equal
#           value: kms-vcluster-pool
#           effect: NoSchedule
#     buildArgs:
#       RUST_IMAGE_VERSION: "${RUST_IMAGE_VERSION}"


#   core-client:
#     image: hub.zama.org/dev-kms/core-client
#     tags:
#       - ${TAG_NAME}
#     dockerfile: ./docker/core-client/Dockerfile
#     context: .
#     rebuildStrategy: ignoreContextChanges
#     createPullSecret: false
#     kaniko:
#       initImage: "public.ecr.aws/docker/library/alpine:latest"
#       pullSecret: registry-credentials
#       resources:
#         requests:
#           memory: "128Gi"
#           cpu: "64"
#         limits:
#           memory: "128Gi"
#           cpu: "64"
#       cache: true
#       args:
#         - "--custom-platform=linux/amd64"
#         - "--cache-run-layers=true"
#         - "--cache-copy-layers=true"
#       tolerations:
#         - key: karpenter.sh/nodepool
#           operator: Equal
#           value: kms-vcluster-pool
#           effect: NoSchedule
#     buildArgs:
#       RUST_IMAGE_VERSION: "${RUST_IMAGE_VERSION}"

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  tkms-infra:
    namespace: ${NAMESPACE}
    helm:
      releaseName: tkms-infra
      chart:
        name: oci://ghcr.io/zama-zws/crossplane/tkms-infra
        version: "${TKMS_INFRA_CHART_VERSION}"
      values:
        fullnameOverride: "kms-party-${DEVSPACE_NAMESPACE}"
        publicBucketVault:
          irsa:
            serviceAccountName: ${DEVSPACE_NAMESPACE}
          labels:
            environment: ${DEVSPACE_NAMESPACE}
        kmsParties:
          serviceAccountPrefixName: ${DEVSPACE_NAMESPACE}
          publishConnectionDetailsTo:
            prefixName: ${DEVSPACE_NAMESPACE}
          publicBucketVaultRef:
            matchLabels:
              environment: ${DEVSPACE_NAMESPACE}
          awsKms:
            recipientAttestationImageSHA384: "${{ env.PCR0 }}"
          enclaveNodeGroup:
            taint:
              - key: "app"
                value: "${DEVSPACE_NAMESPACE}"
                effect: NO_SCHEDULE
      valuesFiles:
        - "./ci/kube-testing/thresholdWithEnclave/tkms-infra/values-kms-enclave-ci.yaml"
  # localstack:
  #   namespace: ${NAMESPACE}
  #   helm:
  #     releaseName: localstack
  #     chart:
  #       name: localstack
  #       repo: https://localstack.github.io/helm-charts
  #     valuesFiles:
  #       - "./ci/kube-testing/infra/localstack-s3-vcluster-values.yaml"
  kms-core-1:
    namespace: "${NAMESPACE}"
    updateImageTags: false
    helm:
      releaseName: kms-service-threshold-1-${DEVSPACE_NAMESPACE}
      chart:
        path: ./charts/kms-core
      values:
        kmsPeers:
          id: 1
        kmsCore:
          image:
            name: hub.zama.org/dev-kms/core-service
            tag: "${TAG_NAME}"
        kmsCoreClient:
          image:
            name: hub.zama.org/dev-kms/core-client
            tag: "${TAG_NAME}"
      valuesFiles:
        - "./ci/kube-testing/kms/values-${DEVSPACE_NAMESPACE}-vcluster.yaml"
  kms-core-2:
    namespace: ${NAMESPACE}
    updateImageTags: false
    helm:
      releaseName: kms-service-threshold-2-${DEVSPACE_NAMESPACE}
      chart:
        path: ./charts/kms-core
      values:
        kmsPeers:
          id: 2
        kmsCore:
          image:
            name: hub.zama.org/dev-kms/core-service
            tag: ${TAG_NAME}
        kmsCoreClient:
          image:
            name: hub.zama.org/dev-kms/core-client
            tag: ${TAG_NAME}
      valuesFiles:
        - "./ci/kube-testing/kms/values-${DEVSPACE_NAMESPACE}-vcluster.yaml"
  kms-core-3:
    namespace: ${NAMESPACE}
    updateImageTags: false
    helm:
      releaseName: kms-service-threshold-3-${DEVSPACE_NAMESPACE}
      chart:
        path: ./charts/kms-core
      values:
        kmsPeers:
          id: 3
        kmsCore:
          image:
            name: hub.zama.org/dev-kms/core-service
            tag: ${TAG_NAME}
        kmsCoreClient:
          image:
            name: hub.zama.org/dev-kms/core-client
            tag: ${TAG_NAME}
      valuesFiles:
          - "./ci/kube-testing/kms/values-${DEVSPACE_NAMESPACE}-vcluster.yaml"
  kms-core-4:
    namespace: ${NAMESPACE}
    updateImageTags: false
    helm:
      releaseName: kms-service-threshold-4-${DEVSPACE_NAMESPACE}
      chart:
        path: ./charts/kms-core
      values:
        kmsPeers:
          id: 4
        kmsCore:
          image:
            name: hub.zama.org/dev-kms/core-service
            tag: ${TAG_NAME}
        kmsCoreClient:
          image:
            name: hub.zama.org/dev-kms/core-client
            tag: ${TAG_NAME}
      valuesFiles:
        - "./ci/kube-testing/kms/values-${DEVSPACE_NAMESPACE}-vcluster.yaml"
  kms-core-init:
    namespace: ${NAMESPACE}
    updateImageTags: false
    helm:
      releaseName: kms-core-init-${DEVSPACE_NAMESPACE}
      chart:
        path: ./charts/kms-core
      values:
        kmsCore:
          image:
            name: hub.zama.org/dev-kms/core-service
            tag: ${TAG_NAME}
        kmsCoreClient:
          image:
            name: hub.zama.org/dev-kms/core-client
            tag: ${TAG_NAME}
      valuesFiles:
        - "./ci/kube-testing/kms/values-kms-service-init-${DEVSPACE_NAMESPACE}-vcluster.yaml"

dev:
  core1:
    labelSelector:
      app.kubernetes.io/name: kms-service-threshold-1-${DEVSPACE_NAMESPACE}-core
    ports:
      - port: 50100:50100
  core2:
    labelSelector:
      app.kubernetes.io/name: kms-service-threshold-2-${DEVSPACE_NAMESPACE}-core
    ports:
      - port: 50200:50100
  core3:
    labelSelector:
      app.kubernetes.io/name: kms-service-threshold-3-${DEVSPACE_NAMESPACE}-core
    ports:
      - port: 50300:50100
  core4:
    labelSelector:
      app.kubernetes.io/name: kms-service-threshold-4-${DEVSPACE_NAMESPACE}-core
    ports:
      - port: 50400:50100
  localstack:
    labelSelector:
      app.kubernetes.io/name: localstack
    ports:
      - port: 9000:4566
# This is a list of `dev` containers that are based on the containers created by your deployments
# dev:
#   app:
#     # Search for the container that runs this image
#     imageSelector: ghcr.io/zama-ai/kms/core-service:latest
#     # Replace the container image with this dev-optimized image (allows to skip image building during development)
#     devImage: ghcr.io/loft-sh/devspace-containers/rust:1.67-alpine
#     # Sync files between the local filesystem and the development container
#     sync:
#       - path: ./
#         uploadExcludeFile: .dockerignore
#     # Open a terminal and use the following command to start it
#     terminal:
#       command: ./devspace_start.sh
#     # Inject a lightweight SSH server into the container (so your IDE can connect to the remote dev env)
#     ssh:
#       enabled: true
#     # Make the following commands from my local machine available inside the dev container
#     proxyCommands:
#       - command: devspace
#       - command: kubectl
#       - command: helm
#       - gitCredentials: true
#     # Forward the following ports to be able access your application via localhost
#     ports:
#       - port: "50100"
#     # Open the following URLs once they return an HTTP status code other than 502 or 503
#     open:
#       - url: http://localhost:50100

# # Use the `commands` section to define repeatable dev workflows for this project
# commands:
#   migrate-db:
#     command: |-
#       echo 'This is a cross-platform, shared command that can be used to codify any kind of dev task.'
#       echo 'Anyone using this project can invoke it via "devspace run migrate-db"'

# Define dependencies to other projects with a devspace.yaml
# dependencies:
#   api:
#     git: https://...  # Git-based dependencies
#     tag: v1.0.0
#   ui:
#     path: ./ui        # Path-based dependencies (for monorepos)
