[workspace.metadata.dylint]
libraries = [
    { git = "https://github.com/trailofbits/dylint", pattern = "examples/general/non_local_effect_before_unhandled_error" },
]

[non_local_effect_before_unhandled_error]
work_limit = 100000000
