build-compose-base:
	docker compose -vvv -f docker-compose-core-base.yml build

build-compose-threshold:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-threshold.yml build

start-compose-threshold:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-threshold.yml up -d --wait

stop-compose-threshold:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-threshold.yml down --volumes --remove-orphans

build-compose-centralized:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-centralized.yml build

start-compose-centralized:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-centralized.yml up -d --wait

stop-compose-centralized:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-centralized.yml down --volumes --remove-orphans

start-compose-threshold-telemetry:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-threshold.yml -f docker-compose-telemetry.yml up -d --wait

stop-compose-threshold-telemetry:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-threshold.yml -f docker-compose-telemetry.yml down --volumes --remove-orphans

# Test backwards compatibility with LFS files. This will pull the LFS files from git before running the tests.
test-backward-compatibility: pull-lfs-files
	cargo test --test backward_compatibility_* -- --include-ignored

# Do not run LFS pull and use locally generated files to test backward compatibility.
test-backward-compatibility-local:
	cargo test --test backward_compatibility_* -- --include-ignored --no-capture

# Frozen — generators may be non-deterministic. Their data is committed and
# must NOT be deleted or regenerated by `generate-backward-compatibility-all`.
FROZEN_BWC_VERSIONS := 0.11.0 0.11.1 0.13.0 0.13.10 0.13.20

# Deterministic — re-running produces byte-identical output.
# `generate-backward-compatibility-all` cleans and regenerates these.
DETERMINISTIC_BWC_VERSIONS :=

# Derived data-dir paths (e.g. 0.14.0 -> backward-compatibility/data/0_14_0)
DETERMINISTIC_BWC_DIRS := $(addprefix backward-compatibility/data/,$(subst .,_,$(DETERMINISTIC_BWC_VERSIONS)))

clean-backward-compatibility-data:
	@# Only deterministic-version dirs are removed. Frozen dirs and the shared
	@# .ron files are preserved so committed frozen entries survive.
	@if [ -n "$(DETERMINISTIC_BWC_DIRS)" ]; then rm -rf $(DETERMINISTIC_BWC_DIRS); fi

# Use the version-specifc generators only if you really need it,
# e.g., when a type is added in a minor release.
generate-backward-compatibility-v0.13.0:
	cd backward-compatibility/generate-v0.13.0 && cargo run --release

generate-backward-compatibility-v0.13.10:
	cd backward-compatibility/generate-v0.13.10 && cargo run --release

generate-backward-compatibility-v0.13.20:
	cd backward-compatibility/generate-v0.13.20 && cargo run --release

generate-backward-compatibility-all: clean-backward-compatibility-data $(addprefix generate-backward-compatibility-v,$(DETERMINISTIC_BWC_VERSIONS))
	@echo "Generated backward compatibility data for deterministic versions: $(DETERMINISTIC_BWC_VERSIONS)"

# Test material generation targets
generate-test-material-all:
	cargo run -p generate-test-material -- --output ./test-material --verbose --profile insecure --parties 4
	cargo run -p generate-test-material -- --output ./test-material --verbose --profile secure --parties 4,13

generate-test-material-testing:
	@echo "Generating testing material..."
	cargo run -p generate-test-material -- --output ./test-material --verbose --profile insecure --parties 4

generate-test-material-default:
	cargo run -p generate-test-material -- --output ./test-material --verbose --profile secure --parties 4,13

validate-test-material:
	cargo run -p generate-test-material -- --output ./test-material --verbose validate

clean-test-material:
	cargo run -p generate-test-material -- --output ./test-material --verbose clean

# Check if Git LFS is installed and enabled
check-git-lfs:
	@if git lfs version > /dev/null 2>&1; then \
		echo "Git LFS is installed and enabled."; \
	else \
		echo "Error: Git LFS is not installed or not enabled. Please"; \
		exit 1; \
	fi

pull-lfs-files: check-git-lfs
	git lfs pull

linting-all:
	cargo clippy --all-targets --all-features -- -D warnings

linting-package:
	@if [ -z "$(PACKAGE)" ]; then \
		echo "Error: PACKAGE is not set. Usage: make clippy-package PACKAGE=<package-name>"; \
		exit 1; \
	fi
	cargo clippy --all-targets --all-features --package $(PACKAGE) -- -D warnings
