build-compose-base:
	docker compose -vvv -f docker-compose-core-base.yml build

build-compose-threshold:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-threshold.yml build

start-compose-threshold:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-threshold.yml up -d --wait

stop-compose-threshold:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-threshold.yml down --volumes --remove-orphans

build-compose-centralized:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-centralized.yml build

start-compose-centralized:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-centralized.yml up -d --wait

stop-compose-centralized:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-centralized.yml down --volumes --remove-orphans

start-compose-threshold-telemetry:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-threshold.yml -f docker-compose-telemetry.yml up -d --wait

stop-compose-threshold-telemetry:
	docker compose -vvv -f docker-compose-core-base.yml -f docker-compose-core-threshold.yml -f docker-compose-telemetry.yml down --volumes --remove-orphans

TFHE_LINTS_GIT := https://github.com/zama-ai/tfhe-rs
TFHE_LINTS_TAG := tfhe-rs-1.6.1
TFHE_LINTS_TOOLCHAIN := nightly-2026-01-22
SNAPSHOT_PACKAGES ?= kms kms-grpc threshold-execution threshold-algebra threshold-networking threshold-types
TFHE_SNAPSHOT_PATTERN := utils/tfhe-lints/snapshot

ifeq ($(SKIP_TFHE_SNAPSHOT_TOOL_INSTALL),1)
TFHE_SNAPSHOT_TOOL_DEP :=
else
TFHE_SNAPSHOT_TOOL_DEP := install-tfhe-snapshot-tools
endif

# Test backwards compatibility with LFS files. This will pull the LFS files from git before running the tests.
test-backward-compatibility: pull-lfs-files
	cargo test --test backward_compatibility_* -- --include-ignored

# Do not run LFS pull and use locally generated files to test backward compatibility.
test-backward-compatibility-local:
	cargo test --test backward_compatibility_* -- --include-ignored --no-capture

# Frozen — generators may be non-deterministic. Their data is committed and
# must NOT be deleted or regenerated by `generate-backward-compatibility-all`.
FROZEN_BWC_VERSIONS := 0.11.0 0.11.1 0.13.0 0.13.10 0.13.20

# Deterministic — re-running produces byte-identical output.
# `generate-backward-compatibility-all` cleans and regenerates these.
DETERMINISTIC_BWC_VERSIONS := 0.14.0

# Derived data-dir paths (e.g. 0.14.0 -> backward-compatibility/data/0_14_0)
DETERMINISTIC_BWC_DIRS := $(addprefix backward-compatibility/data/,$(subst .,_,$(DETERMINISTIC_BWC_VERSIONS)))

clean-backward-compatibility-data:
	@# Only deterministic-version dirs are removed. Frozen dirs and the shared
	@# .ron files are preserved so committed frozen entries survive.
	@if [ -n "$(DETERMINISTIC_BWC_DIRS)" ]; then rm -rf $(DETERMINISTIC_BWC_DIRS); fi

# Use the version-specific generators only if you really need it,
# e.g., when a type is added in a minor release.
generate-backward-compatibility-v0.13.0:
	cd backward-compatibility/generate-v0.13.0 && cargo run --release

generate-backward-compatibility-v0.13.10:
	cd backward-compatibility/generate-v0.13.10 && cargo run --release

generate-backward-compatibility-v0.13.20:
	cd backward-compatibility/generate-v0.13.20 && cargo run --release

generate-backward-compatibility-v0.14.0:
	cd backward-compatibility/generate-v0.14.0 && cargo run --release

generate-backward-compatibility-all: clean-backward-compatibility-data $(addprefix generate-backward-compatibility-v,$(DETERMINISTIC_BWC_VERSIONS))
	@echo "Generated backward compatibility data for deterministic versions: $(DETERMINISTIC_BWC_VERSIONS)"

install-tfhe-snapshot-tools:
	cargo install cargo-dylint dylint-link --locked
	rustup toolchain install $(TFHE_LINTS_TOOLCHAIN) --component llvm-tools-preview,rustc-dev
	cargo install --force --git $(TFHE_LINTS_GIT) --tag $(TFHE_LINTS_TAG) tfhe-backward-compat-checker --locked

backward-snapshot: $(TFHE_SNAPSHOT_TOOL_DEP)
	@if [ -z "$(SNAPSHOT_OUTPUT_DIR)" ]; then \
		echo "Error: SNAPSHOT_OUTPUT_DIR is not set. Usage: make backward-snapshot SNAPSHOT_OUTPUT_DIR=<dir>"; \
		exit 1; \
	fi
	@mkdir -p "$(abspath $(SNAPSHOT_OUTPUT_DIR))"
	@rm -f "$(abspath $(SNAPSHOT_OUTPUT_DIR))"/lint_enum_snapshots_*.json
	@for package in $(SNAPSHOT_PACKAGES); do \
		echo "Generating backward compatibility snapshot for $$package"; \
		CARGO_TARGET_DIR="$(abspath $(SNAPSHOT_OUTPUT_DIR))/cargo-target" cargo clean -p "$$package" --profile dev; \
		CARGO_TARGET_DIR="$(abspath $(SNAPSHOT_OUTPUT_DIR))/cargo-target" TFHE_BACKWARD_COMPAT_DATA_DIR="$(abspath $(SNAPSHOT_OUTPUT_DIR))" cargo dylint \
			--git $(TFHE_LINTS_GIT) \
			--tag $(TFHE_LINTS_TAG) \
			--pattern $(TFHE_SNAPSHOT_PATTERN) \
			--all \
			--no-deps \
			-p "$$package" -- --all-features; \
	done

backward-snapshot-worktree: $(TFHE_SNAPSHOT_TOOL_DEP)
	@if [ -z "$(BASE_REF)" ]; then \
		echo "Error: BASE_REF is not set. Usage: make backward-snapshot-worktree BASE_REF=<ref> SNAPSHOT_OUTPUT_DIR=<dir>"; \
		exit 1; \
	fi
	@if [ -z "$(SNAPSHOT_OUTPUT_DIR)" ]; then \
		echo "Error: SNAPSHOT_OUTPUT_DIR is not set. Usage: make backward-snapshot-worktree BASE_REF=<ref> SNAPSHOT_OUTPUT_DIR=<dir>"; \
		exit 1; \
	fi
	@tmp_parent="$$(mktemp -d)"; \
	worktree_dir="$$tmp_parent/worktree"; \
	trap 'git worktree remove --force "$$worktree_dir" >/dev/null 2>&1 || true; rm -rf "$$tmp_parent"' EXIT; \
	git worktree add --detach "$$worktree_dir" "$(BASE_REF)"; \
	mkdir -p "$(abspath $(SNAPSHOT_OUTPUT_DIR))"; \
	rm -f "$(abspath $(SNAPSHOT_OUTPUT_DIR))"/lint_enum_snapshots_*.json; \
	for package in $(SNAPSHOT_PACKAGES); do \
		echo "Generating base backward compatibility snapshot for $$package at $(BASE_REF)"; \
		(cd "$$worktree_dir" && CARGO_TARGET_DIR="$(abspath $(SNAPSHOT_OUTPUT_DIR))/cargo-target" cargo clean -p "$$package" --profile dev && CARGO_TARGET_DIR="$(abspath $(SNAPSHOT_OUTPUT_DIR))/cargo-target" TFHE_BACKWARD_COMPAT_DATA_DIR="$(abspath $(SNAPSHOT_OUTPUT_DIR))" cargo dylint \
			--git $(TFHE_LINTS_GIT) \
			--tag $(TFHE_LINTS_TAG) \
			--pattern $(TFHE_SNAPSHOT_PATTERN) \
			--all \
			--no-deps \
			-p "$$package" -- --all-features); \
	done

backward-snapshot-check: $(TFHE_SNAPSHOT_TOOL_DEP)
	@if [ -z "$(BASE_REF)" ]; then \
		echo "Error: BASE_REF is not set. Usage: make backward-snapshot-check BASE_REF=<ref>"; \
		exit 1; \
	fi
	@base_dir="$$(mktemp -d)"; \
	head_dir="$$(mktemp -d)"; \
	trap 'rm -rf "$$base_dir" "$$head_dir"' EXIT; \
	$(MAKE) backward-snapshot-worktree BASE_REF="$(BASE_REF)" SNAPSHOT_OUTPUT_DIR="$$base_dir" SNAPSHOT_PACKAGES="$(SNAPSHOT_PACKAGES)" SKIP_TFHE_SNAPSHOT_TOOL_INSTALL=1; \
	$(MAKE) backward-snapshot SNAPSHOT_OUTPUT_DIR="$$head_dir" SNAPSHOT_PACKAGES="$(SNAPSHOT_PACKAGES)" SKIP_TFHE_SNAPSHOT_TOOL_INSTALL=1; \
	tfhe-backward-compat-checker check --base-dir "$$base_dir" --head-dir "$$head_dir"

backward-snapshot-report: $(TFHE_SNAPSHOT_TOOL_DEP)
	@if [ -z "$(BASE_REF)" ]; then \
		echo "Error: BASE_REF is not set. Usage: make backward-snapshot-report BASE_REF=<ref> OUTPUT_FILE=<path>"; \
		exit 1; \
	fi
	@if [ -z "$(OUTPUT_FILE)" ]; then \
		echo "Error: OUTPUT_FILE is not set. Usage: make backward-snapshot-report BASE_REF=<ref> OUTPUT_FILE=<path>"; \
		exit 1; \
	fi
	@base_dir="$$(mktemp -d)"; \
	head_dir="$$(mktemp -d)"; \
	trap 'rm -rf "$$base_dir" "$$head_dir"' EXIT; \
	$(MAKE) backward-snapshot-worktree BASE_REF="$(BASE_REF)" SNAPSHOT_OUTPUT_DIR="$$base_dir" SNAPSHOT_PACKAGES="$(SNAPSHOT_PACKAGES)" SKIP_TFHE_SNAPSHOT_TOOL_INSTALL=1; \
	$(MAKE) backward-snapshot SNAPSHOT_OUTPUT_DIR="$$head_dir" SNAPSHOT_PACKAGES="$(SNAPSHOT_PACKAGES)" SKIP_TFHE_SNAPSHOT_TOOL_INSTALL=1; \
	tfhe-backward-compat-checker diff-report --base-dir "$$base_dir" --head-dir "$$head_dir" --output "$(abspath $(OUTPUT_FILE))"

# Test material generation targets
generate-test-material-all:
	cargo run -p generate-test-material -- --output ./test-material --verbose --profile insecure --parties 4
	cargo run -p generate-test-material -- --output ./test-material --verbose --profile secure --parties 4,13

generate-test-material-testing:
	@echo "Generating testing material..."
	cargo run -p generate-test-material -- --output ./test-material --verbose --profile insecure --parties 4

generate-test-material-default:
	cargo run -p generate-test-material -- --output ./test-material --verbose --profile secure --parties 4,13

validate-test-material:
	cargo run -p generate-test-material -- --output ./test-material --verbose validate

clean-test-material:
	cargo run -p generate-test-material -- --output ./test-material --verbose clean

# Check if Git LFS is installed and enabled
check-git-lfs:
	@if git lfs version > /dev/null 2>&1; then \
		echo "Git LFS is installed and enabled."; \
	else \
		echo "Error: Git LFS is not installed or not enabled. Please"; \
		exit 1; \
	fi

pull-lfs-files: check-git-lfs
	git lfs pull


# `DYLINT_RUSTFLAGS` is consumed by `cargo-dylint` and forwarded to the `rustc`
# driver that runs each Dylint library. Here it turns warnings to errors so Dylint
# findings fail CI, while disabling the tfhe-rs `serialize_without_versionize`
# lint, which is intentionally too broad for this workspace. `-Aunknown-lints`
# is paired with it because `cargo dylint --all` loads multiple lint
# libraries/toolchains; libraries that do not define
# `serialize_without_versionize` would otherwise emit an "unknown lint" warning
# for the command-line allow.
DYLINT_RUSTFLAGS ?= -D warnings -Aunknown-lints -Aserialize_without_versionize

lint:
	cargo clippy --all-targets --all-features -- -D warnings

lint-package:
	@if [ -z "$(PACKAGE)" ]; then \
		echo "Error: PACKAGE is not set. Usage: make lint-package PACKAGE=<package-name>"; \
		exit 1; \
	fi
	cargo clippy --all-targets --all-features --package $(PACKAGE) -- -D warnings

# The nightly toolchain and components needed to build each Dylint library are
# auto-installed by rustup on the first `cargo dylint --all` run, driven by the
# `rust-toolchain` file each library ships (e.g. `tfhe-lints` in the tfhe-rs
# repo at the tag pinned in `dylint.toml`).
install-dylint:
	cargo install cargo-dylint dylint-link --locked

lint-dylint:
	DYLINT_RUSTFLAGS="$(DYLINT_RUSTFLAGS)" cargo dylint --all
