// The JS tests load a *stable* JSON test vector (see
// `TestingUserDecryptionTranscript::to_stable_test_vector` on the Rust side).
// Every field of the JSON maps directly onto an argument of the stable public
// WASM API, so an older published `tkms`/ `node-tkms` build can be exercised
// against a vector generated by a newer KMS.

const fs = require('node:fs');
const test = require('node:test');
const assert = require('node:assert').strict
const {
    ml_kem_pke_keygen,
    ml_kem_pke_get_pk,
    ml_kem_pke_encrypt,
    ml_kem_pke_decrypt,
    ml_kem_pke_pk_to_u8vec,
    ml_kem_pke_sk_to_u8vec,
    ml_kem_pke_pk_len,
    ml_kem_pke_sk_len,
    process_user_decryption_resp_from_js,
    u8vec_to_ml_kem_pke_pk,
    u8vec_to_ml_kem_pke_sk,
    new_client,
    new_server_id_addr,
} = require("../../pkg");

// Decode a hex string (with or without a leading "0x") into a Uint8Array.
function hexToBytes(hex) {
    const clean = hex.startsWith('0x') ? hex.slice(2) : hex;
    const out = new Uint8Array(clean.length / 2);
    for (let i = 0; i < out.length; i++) {
        out[i] = parseInt(clean.substr(i * 2, 2), 16);
    }
    return out;
}

// Interpret a big-endian byte array as a BigInt (the WASM API returns plaintext bytes in BE).
function beBytesToBigInt(bytes) {
    let acc = 0n;
    for (const b of bytes) {
        acc = (acc << 8n) | BigInt(b);
    }
    return acc;
}

// Interpret a little-endian byte array as a BigInt (the stable vector stores plaintexts in LE).
function leBytesToBigInt(bytes) {
    let acc = 0n;
    for (let i = bytes.length - 1; i >= 0; i--) {
        acc = (acc << 8n) | BigInt(bytes[i]);
    }
    return acc;
}

// Load the stable JSON test vector and reconstruct the inputs to the stable WASM API.
function loadVector(path) {
    const data = JSON.parse(fs.readFileSync(path));
    const server_addrs = data.server_addrs.map(s => new_server_id_addr(s.id, s.addr));
    const client = new_client(server_addrs, data.client_address, data.fhe_parameter);
    const enc_pk = u8vec_to_ml_kem_pke_pk(hexToBytes(data.enc_pk));
    const enc_sk = u8vec_to_ml_kem_pke_sk(hexToBytes(data.enc_sk));
    return { data, client, enc_pk, enc_sk };
}

// Assert that the decrypted plaintexts (BE) match the expected plaintexts (LE) from the vector.
function assertExpected(result, expected) {
    assert.deepEqual(result.length, expected.length);
    for (let i = 0; i < expected.length; i++) {
        assert.deepEqual(result[i].fhe_type, expected[i].fhe_type);
        assert.deepEqual(
            beBytesToBigInt(result[i].bytes),
            leBytesToBigInt(hexToBytes(expected[i].plaintext_hex)),
        );
    }
}

test('pke', (_t) => {
    let sk = ml_kem_pke_keygen();
    let pk = ml_kem_pke_get_pk(sk);

    // try to serialize
    let pk_buf = ml_kem_pke_pk_to_u8vec(pk);
    let sk_buf = ml_kem_pke_sk_to_u8vec(sk);

    // there is extra 8 bytes in the bincode encoding to encode the vector length
    // see https://github.com/bincode-org/bincode/blob/trunk/docs/spec.md#linear-collections-vec-arrays-etc
    assert.deepEqual(ml_kem_pke_sk_len() + 8, sk_buf.length);

    // since this is serialized using safe_serialization,
    // we just checke that the length is within a certain range
    assert(pk_buf.length > ml_kem_pke_pk_len());
    assert(pk_buf.length < ml_kem_pke_pk_len() + 100); // the metadata should not be more than 100 bytes

    // try to deserialize
    let sk_2 = u8vec_to_ml_kem_pke_sk(sk_buf);
    let pk_2 = u8vec_to_ml_kem_pke_pk(pk_buf);

    const x = new Uint8Array([21, 31, 1, 2, 3]);
    let ct = ml_kem_pke_encrypt(x, pk_2);
    let pt = ml_kem_pke_decrypt(ct, sk_2);
    assert.deepEqual(x, pt);
});

test('centralized user decryption response', (_t) => {
    // TEST_CENTRAL_WASM_TRANSCRIPT_PATH
    const { data, client, enc_pk, enc_sk } = loadVector('temp/test-central-wasm-transcript.8.json');

    // with verification, using the request and eip712 domain from the vector
    const pt = process_user_decryption_resp_from_js(
        client, data.request, data.eip712_domain, data.responses, enc_pk, enc_sk, data.threshold, true);
    assertExpected(pt, data.expected);

    // without verification (insecure path): no request nor domain is needed
    const pt2 = process_user_decryption_resp_from_js(
        client, null, null, data.responses, enc_pk, enc_sk, data.threshold, false);
    assertExpected(pt2, data.expected);
});

test('threshold user decryption response', (_t) => {
    // TEST_THRESHOLD_WASM_TRANSCRIPT_PATH
    const { data, client, enc_pk, enc_sk } = loadVector('temp/test-threshold-wasm-transcript.8.json');

    // with verification, threshold inferred from the number of servers (null)
    const pt = process_user_decryption_resp_from_js(
        client, data.request, data.eip712_domain, data.responses, enc_pk, enc_sk, null, true);
    assertExpected(pt, data.expected);

    // with verification and the explicit threshold from the vector
    const pt1 = process_user_decryption_resp_from_js(
        client, data.request, data.eip712_domain, data.responses, enc_pk, enc_sk, data.threshold, true);
    assertExpected(pt1, data.expected);

    // without verification (insecure path)
    const pt2 = process_user_decryption_resp_from_js(
        client, null, null, data.responses, enc_pk, enc_sk, null, false);
    assertExpected(pt2, data.expected);

    // reconstruction must still succeed with fewer (but enough) shares
    data.responses.pop();
    const pt3 = process_user_decryption_resp_from_js(
        client, data.request, data.eip712_domain, data.responses, enc_pk, enc_sk, null, true);
    assertExpected(pt3, data.expected);
});

test('new client', (_t) => {
    // make a generic client
    let address = "0x66f9664f97F2b50F62D13eA064982f936dE76657";
    new_client([new_server_id_addr(1, address)], address, 'default');
    new_client([new_server_id_addr(2, address), new_server_id_addr(1, address)], address, 'default');

    // we only need to test the constructor, no need to test is further
    // as they are handled by the other tests
});

test('new client repeated ID', (_t) => {
    let address = "0x66f9664f97F2b50F62D13eA064982f936dE76657";
    // expect to throw error if there are duplicate IDs
    assert.throws(
        () => new_client([new_server_id_addr(1, address), new_server_id_addr(1, address)], address, 'default'),
        Error
    );
});
