# Config for a centralized deployment of n=1 core with threshold t=0

# The type of the KMS ("centralized" or "threshold")
kms_type = "centralized"

# The minimum number of matching responses required to have an honest majority
num_majority = 1

# The minimum number of responses required to reconstruct a value (e.g. in user decryption)
num_reconstruct = 1

# Decryption mode used in user decryption reconstruction.
# Options are NoiseFloodSmall and BitDecSmall.
# Must match the deployed core/service setting!
# Only relevant for threshold.
decryption_mode = "NoiseFloodSmall"

# fhe_params = "Test" # Small, insecure parameters for testing
fhe_params = "Default" # Large, secure parameters

# List of connection info to each of the cores (in the centralized case, there will only be a single core)
[[cores]]
# The ID of the given KMS server (monotonically increasing positive integer starting at 1) 
# (in the centralized case it must be 1)
party_id = 1
# The address of the given KMS server, including the port
address = "localhost:50051"
# The S3 endpoint where the public material of the given server can be reached
s3_endpoint = "http://localhost:9000/kms"
# The folder at the S3 endpoint where the data is stored
object_folder = "PUB"
