kmsInit:
  enabled: true

minio:
  enabled: true
  endpoint: "http://localstack:4566"
  username: kms-access-key-id
  password: kms-secret-access-key

kmsCoreClient:
  enabled: true
  nameOverride: kms-core-client
  image:
    name: ghcr.io/zama-ai/kms/core-client
    tag:
  num_majority: 2 # 2 when 4 parties and 5 when 13 parties
  num_reconstruct: 3 # 3 when 4 parties and 9 when 13 parties
  decryption_mode: NoiseFloodSmall
  fhe_parameter: Test
  #=============================================================
  #==========RESOURCERS TO ADJUST BASED ON ENVIRONMENT==========
  # If you launch the deployment locally, adjust these resources
  # according to your system and available resources
  resources:
    requests:
      memory: 24Gi
      cpu: 12
    limits:
      memory: 24Gi
      cpu: 12
  #=============================================================
kubeUtils:
  image:
    name: ghcr.io/zama-ai/security-hub/infra/kube-utils
    tag: v0.4.3
    pullPolicy: Always

kmsCore:
  enabled: false
  thresholdMode:
    enabled: true
    initializationScript:
      enabled: true
    peersList:
      - id: 1
        host: kms-service-threshold-1-<namespace>-core-1
        port: 50001
      - id: 2
        host: kms-service-threshold-2-<namespace>-core-2
        port: 50001
      - id: 3
        host: kms-service-threshold-3-<namespace>-core-3
        port: 50001
      - id: 4
        host: kms-service-threshold-4-<namespace>-core-4
        port: 50001

kmsGenKeys:
  enabled: false
kmsGenCertAndKeys:
  enabled: false
