// This file is @generated by prost-build.
/// Module is the config object for the genutil module.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Module {}
impl ::prost::Name for Module {
    const NAME: &'static str = "Module";
    const PACKAGE: &'static str = "cosmos.genutil.module.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.genutil.module.v1.Module".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.genutil.module.v1.Module".into()
    }
}
