# Deployment Type Options:
# - centralized: Deploy only public vault with IRSA.
# - centralizedWithEnclave: Deploy public vault with IRSA and enclave enabled.
# - threshold: Deploy public vault without IRSA and KMS parties without enclave.
# - thresholdWithEnclave: Deploy public vault without IRSA and KMS parties with enclave enabled.
deploymentType: centralizedWithEnclave

region: eu-west-1
environment: zws-dev
fullnameOverride: kms-party-kms-enclave-ci

publicBucketVault:
  enabled: true
  irsa:
    enabled: true
    serviceAccountName: kms-enclave-ci
  deletionPolicy: Delete
  labels:
    environment: kms-enclave-ci
  configMapTargetRef:
    enabled: true
    name: kms-bucket-vault
  tags:
    Environment: zws-dev
    ManagedBy: zama

kmsParties:
  enabled: true
  serviceAccountPrefixName: kms-enclave-ci
  publishConnectionDetailsTo:
    # This is the prefix name of the ConfigMap that will be created : <prefixName>-<index>
    prefixName: kms-enclave-ci
  tags:
    Environment: zws-dev
    ManagedBy: zama
  replicas: 1
  # matchExistingName allows to reference an existing public bucket vault if it already exists
  publicBucketVaultRef:
    # This is the existing name of the public bucket vault that will be used to reference
    # matchExistingName: kms-bucket-vault-with-enclave
    # This is the k8s label of the public bucket vault that will be used to reference
    matchLabels:
      environment: kms-enclave-ci

  # RDS Connector database configuration
  connectorDatabase:
    enabled: false
