kmsCore:
  enabled: false

kmsCoreClient:
  enabled: true
  nameOverride: kms-core-client-threshold-with-enclave-staging
  image:
    name: ghcr.io/zama-ai/kms/core-client
    tag: <version>
  envFrom:
    configmap:
      name: kms-enclave-ci-1
  num_majority: 5 # 2 when 4 parties and 5 when 13 parties
  num_reconstruct: 9 # 3 when 4 parties and 9 when 13 parties
  decryption_mode: NoiseFloodSmall
  fhe_parameter: Default
  resources:
    requests:
      memory: 24Gi
      cpu: 12
    limits:
      memory: 24Gi
      cpu: 12
  nodeSelector:
    karpenter.sh/nodepool: kms-pool
  tolerations:
    - key: karpenter.sh/nodepool
      effect: NoSchedule
      operator: Equal
      value: kms-pool

kmsInit:
  enabled: true
  nodeSelector:
    karpenter.sh/nodepool: kms-pool
  tolerations:
    - key: karpenter.sh/nodepool
      effect: NoSchedule
      operator: Equal
      value: kms-pool

kmsGenKeys:
  enabled: false

kmsGenCertAndKeys:
  enabled: false

kmsCoreClientTesting:
  enabled: false
  # schedule: "5 * * * *"
  shell_command: []
    # - date
    # - export CORE_CLIENT__FHE_PARAMS=Default && ./bin/kms-core-client --logs -f config.toml decrypt -d euint8 -k 8e53e2d84ecdd37e344ec414fe6804b57c1eb8f26a2bbcc2818ebabe81b58673 -e ff --precompute-sns
    # - date
