[package]
name = "tests-utils"
version.workspace = true
authors.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
# ⚠️ IMPORTANT: Add new dependencies to workspace root Cargo.toml, NOT here!
# Use .workspace = true to reference workspace dependencies
# Maintain alphabetical order
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
