# Deployment Type Options:
# - centralized: Deploy only public vault with IRSA.
# - centralizedWithEnclave: Deploy public vault with IRSA and enclave enabled.
# - threshold: Deploy public vault without IRSA and KMS parties without enclave.
# - thresholdWithEnclave: Deploy public vault without IRSA and KMS parties with enclave enabled.
deploymentType: centralizedWithEnclave

region: eu-west-1
environment: zws-dev
fullnameOverride: kms-party-kms-enclave-ci

publicBucketVault:
  enabled: true
  irsa:
    enabled: true
    serviceAccountName: kms-enclave-ci
  deletionPolicy: Delete
  labels:
    environment: kms-enclave-ci
  configMapTargetRef:
    enabled: false
  tags:
    Environment: zws-dev
    ManagedBy: zama

kmsParties:
  enabled: true
  serviceAccountPrefixName: kms-enclave-ci
  publishConnectionDetailsTo:
    # This is the prefix name of the ConfigMap that will be created : <prefixName>-<index>
    prefixName: kms-enclave-ci
  tags:
    Environment: zws-dev
    ManagedBy: zama
  replicas: 1
  # matchExistingName allows to reference an existing public bucket vault if it already exists
  publicBucketVaultRef:
    # This is the existing name of the public bucket vault that will be used to reference
    # matchExistingName: kms-bucket-vault-with-enclave
    # This is the k8s label of the public bucket vault that will be used to reference
    matchLabels:
      environment: kms-enclave-ci
  # Enclave is only enabled for thresholdWithEnclave deployment type
  awsKms:
    keySpecification: SYMMETRIC_DEFAULT
    # This is the SHA384 hash of the image that will be used to attest the recipient
    recipientAttestationImageSHA384: 0d08c129713aeaf2961029e2123c7e7e001c20e905057fc0117d8d145432b5ad70a42a802ad00499f896767723cce7a7
    deletionWindowInDays: 7
    deletionPolicy: Delete
    # if adminArn is not set, only the root user can be autorized to interact with the KMS key
    # adminArn: ""
  # Create EKS node group
  enclaveNodeGroup:
    enabled: true
    instanceType: c7a.16xlarge
    amiType: AL2023_x86_64_STANDARD
    capacityType: ON_DEMAND
    deletionPolicy: Delete
    # Override resources spec for the enclave node group
    resources:
      cpuAllocatable: 48
      memoryAllocatableInGiB: 96
    # Find the release version here: https://github.com/awslabs/amazon-eks-ami/releases
    releaseVersion: "1.32.3-20250620"
    version: "1.32"
    additionalManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    taint:
      - key: "app"
        value: "kms-enclave-ci"
        effect: NO_SCHEDULE
