externalSecretRegistry:
  enabled: true
  targetSecretName: "registry-credentials"
  dockerCredentialsReference:
    awsSecretName: "common/hub-zama-org-registry-credentials"
    urlProperty: url
    usernameProperty: username
    passwordProperty: password
