# All of the options which can be passed via CLI arguments can also be
# permanently specified in this file.

[advisories]
# RUSTSEC-2023-0071 is not applicable in our use-case.
# RUSTSEC-2026-0049 is not a big deal because in our case it could only be
# triggered when talking to AWS APIs, and it could only allow the attacker to
# force us to accept expired certificates, but the attack scenario when an
# attacker steals the private keys for AWS TLS certificates is going to have
# larger consequences on the world. Additionally, we need to keep the
# "connector-hyper-0-14-x" feature because we need to specify fixed server
# names for TLS connections (because when socat proxies are used, the
# connection goes to localhost and if we don't overload the server names, the
# handshake would fail because localhost isn't sts.*.amazonaws.com).
ignore = ["RUSTSEC-2023-0071", "RUSTSEC-2026-0049"]
informational_warnings = ["unmaintained"]
severity_threshold = "medium"

# Advisory Database Configuration
[database]
path = ".cargo/advisory-db" # Path where advisory git repo will be cloned
url = "https://github.com/RustSec/advisory-db.git" # URL to git repo
fetch = true # Perform a `git fetch` before auditing (default: true)
stale = false # Allow stale advisory DB (i.e. no commits for 90 days, default: false)

# Output Configuration
[output]
deny = [] # exit on error if unmaintained dependencies are found
format = "terminal" # "terminal" (human readable report) or "json"
quiet = false # Only print information on error
show_tree = false # Show inverse dependency trees along with advisories (default: true)

# Target Configuration
[target]
os = "linux"
# arch = "x86_64"

[yanked]
enabled = true # Warn for yanked crates in Cargo.lock (default: true)
update_index = true # Auto-update the crates.io index (default: true)
