# All of the options which can be passed via CLI arguments can also be
# permanently specified in this file.

[advisories]
# RUSTSEC-2023-0071 is not applicable in our use-case.
# RUSTSEC-2026-0049 is not an urgent fix for us. It can only be triggered
# when talking to AWS APIs by allowing the attacker to trick us into accepting
# expired certificates. If AWS's TLS certificates are stolen, the consequences
# are of a different magnitude and not something we can do much about.
# For the time being we also require the "connector-hyper-0-14-x" feature
# because we need to specify fixed server names for TLS connections (because
# when socat proxies are used, the connection goes to localhost and if we don't
# overload the server names, the handshake would fail because localhost isn't
# `sts.*.amazonaws.com`).
# RUSTSEC-2026-0098 and RUSTSEC-2026-0099 can be ignored for now, as they could only be exploited by AWS itself.
# We are currently in the process of removing code that is affected by RUSTSEC-2026-0049, RUSTSEC-2026-0098
#and RUSTSEC-2026-0099, and we will remove the ignores below for them once that is done.
ignore = ["RUSTSEC-2023-0071", "RUSTSEC-2026-0049", "RUSTSEC-2026-0098", "RUSTSEC-2026-0099"]
informational_warnings = ["unmaintained"]
severity_threshold = "medium"

# Advisory Database Configuration
[database]
path = ".cargo/advisory-db" # Path where advisory git repo will be cloned
url = "https://github.com/RustSec/advisory-db.git" # URL to git repo
fetch = true # Perform a `git fetch` before auditing (default: true)
stale = false # Allow stale advisory DB (i.e. no commits for 90 days, default: false)

# Output Configuration
[output]
deny = [] # exit on error if unmaintained dependencies are found
format = "terminal" # "terminal" (human readable report) or "json"
quiet = false # Only print information on error
show_tree = false # Show inverse dependency trees along with advisories (default: true)

# Target Configuration
[target]
os = "linux"
# arch = "x86_64"

[yanked]
enabled = true # Warn for yanked crates in Cargo.lock (default: true)
update_index = true # Auto-update the crates.io index (default: true)
