
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-runner
  namespace: kms-ci

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-runner-role
  namespace: kms-ci
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  - workflowtasksets
  - workflowtaskresults
  - workflowtemplates
  - workflowtemplates/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/exec
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-runner-binding
  namespace: kms-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-runner-role
subjects:
- kind: ServiceAccount
  name: workflow-runner
  namespace: kms-ci
