kmsPeers:
  # Number of replicas managed by each statefulset
  count: 1

kmsConnector:
  enabled: false

kmsCore:
  nameOverride:
  addressOverride:
  image:
    name: ghcr.io/zama-ai/kms/core-service-enclave
    tag: <version>
  envFrom:
    configmap:
      name: kms-enclave-ci-1
      key:
        coreClientS3Endpoint: CORE_CLIENT__S3_ENDPOINT
        privateVaultStorageBucket: KMS_CORE__PRIVATE_VAULT__STORAGE__S3__BUCKET
        privateVaultStoragePrefix: KMS_CORE__PRIVATE_VAULT__STORAGE__S3__PREFIX
        privateVaultKeychainAWSKMSRootKeySpec: KMS_CORE__PRIVATE_VAULT__KEYCHAIN__AWS_KMS__ROOT_KEY_SPEC
        privateVaultKeychainAWSKMSRootKeyID: KMS_CORE__PRIVATE_VAULT__KEYCHAIN__AWS_KMS__ROOT_KEY_ID
        publicVaultStorageBucket: KMS_CORE__PUBLIC_VAULT__STORAGE__S3__BUCKET
        publicVaultStoragePrefix: KMS_CORE__PUBLIC_VAULT__STORAGE__S3__PREFIX
        backupVaultStorageBucket: KMS_CORE__BACKUP_VAULT__STORAGE__S3__BUCKET
        backupVaultStoragePrefix: KMS_CORE__BACKUP_VAULT__STORAGE__S3__PREFIX
        backupVaultKeychainAWSKMSRootKeySpec: KMS_CORE__BACKUP_VAULT__KEYCHAIN__AWS_KMS__ROOT_KEY_SPEC
        backupVaultKeychainAWSKMSRootKeyID: KMS_CORE__BACKUP_VAULT__KEYCHAIN__AWS_KMS__ROOT_KEY_ID
  aws:
    region: eu-west-1
  storage:
    storageClassName: gp3
    capacity: 5Gi
  serviceMonitor:
    enabled: false
  resources:
    requests:
      memory: 4Gi
      cpu: 2
    limits:
      memory: 10Gi
      ephemeralStorage: 1Gi
      grpcTimeout: 360
      grpcMaxMessageSize: 2097520

  nitroEnclave:
    enabled: true
    cpuCount: 48
    memoryGiB: 96

  tolerations:
    - key: app
      effect: NoSchedule
      operator: Equal
      value: kms-enclave-ci

mtls:
  enabled: false

environment: dev

tracing:
  enabled: false
  endpoint: "http://otel-deployment-opentelemetry-collector.observability.svc.cluster.local:4317"
  metrics:
    enabled: false
    interval_sec: 20

socat:
  image:
    name: alpine/socat
    tag: latest

rustLog: info

minio:
  enabled: false
