name: docker-build-manual

on:
  workflow_dispatch:

concurrency:
  group: service-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  golden-image:
    name: docker-build-manual/golden-image (bpr)
    uses: zama-ai/ci-templates/.github/workflows/common-docker.yml@3d8b1adcb5504fef30223016d459e3e38b36f9d1
    permissions:
      actions: read # Required to read workflow run information
      contents: read # Required to checkout repository code
      id-token: write # Required for OIDC authentication
      pull-requests: read # Required to read pull request information
      packages: write # Required to publish Docker images
      attestations: write # Required to create build attestations
    with:
      docker-file: "./docker/base/Dockerfile"
      working-directory: "./base"
      push_image: true
      image-name: 'kms/rust-golden-image'
      app-cache-dir: 'kms-base'
      use-cgr-secrets: true
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      AWS_ACCESS_KEY_S3_USER: ${{ secrets.AWS_ACCESS_KEY_S3_USER }}
      AWS_SECRET_KEY_S3_USER: ${{ secrets.AWS_SECRET_KEY_S3_USER }}
      CGR_USERNAME: ${{ secrets.CGR_USERNAME }}
      CGR_PASSWORD: ${{ secrets.CGR_PASSWORD }}

  core-client:
    name: docker-build-manual/core-client (bpr)
    needs: golden-image
    uses: zama-ai/ci-templates/.github/workflows/common-docker.yml@3d8b1adcb5504fef30223016d459e3e38b36f9d1
    permissions:
      actions: read # Required to read workflow run information
      contents: read # Required to checkout repository code
      id-token: write # Required for OIDC authentication
      pull-requests: read # Required to read pull request information
      packages: write # Required to publish Docker images
      attestations: write # Required to create build attestations
    with:
      docker-file: "./docker/core-client/Dockerfile"
      working-directory: "./core-client"
      push_image: true
      image-name: 'kms/core-client'
      app-cache-dir: 'kms-core-client'
      use-cgr-secrets: true
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      AWS_ACCESS_KEY_S3_USER: ${{ secrets.AWS_ACCESS_KEY_S3_USER }}
      AWS_SECRET_KEY_S3_USER: ${{ secrets.AWS_SECRET_KEY_S3_USER }}
      CGR_USERNAME: ${{ secrets.CGR_USERNAME }}
      CGR_PASSWORD: ${{ secrets.CGR_PASSWORD }}

  core-service:
    name: docker-build-manual/core-service (bpr)
    needs: golden-image
    uses: ./.github/workflows/common-docker-big-instance.yml
    permissions:
      actions: read # Required to read workflow run information
      contents: read # Required to checkout repository code
      id-token: write # Required for OIDC authentication
      pull-requests: read # Required to read pull request information
      packages: write # Required to publish Docker images
      attestations: write # Required to create build attestations
    with:
      docker-file: "./docker/core/service/Dockerfile"
      working-directory: "./core/service"
      push_image: true
      image-name: "kms/core-service"
      app-cache-dir: "kms"
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      AWS_ACCESS_KEY_S3_USER: ${{ secrets.AWS_ACCESS_KEY_S3_USER }}
      AWS_SECRET_KEY_S3_USER: ${{ secrets.AWS_SECRET_KEY_S3_USER }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
      CGR_USERNAME: ${{ secrets.CGR_USERNAME }}
      CGR_PASSWORD: ${{ secrets.CGR_PASSWORD }}

  enclave:
    name: docker-build-manual/enclave (bpr)
    needs:
      - core-service
    uses: ./.github/workflows/common-nitro-enclave.yml
    permissions:
      actions: read # Required to read workflow run information
      contents: write # Required to publish packages
      id-token: write # Required for OIDC token generation
      pull-requests: read # Required to read pull request information
      packages: write # Required to publish packages
      attestations: write # Required to write attestations
    with:
      docker-file-enclave: "./docker/core/service/enclave.dockerfile"
      working-directory: "./core/service"
      push_image: true
      image-name: "kms/core-service"
      image-enclave-name: "kms/core-service-enclave"
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      CGR_USERNAME: ${{ secrets.CGR_USERNAME }}
      CGR_PASSWORD: ${{ secrets.CGR_PASSWORD }}
