name: helm-lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    name: helm-lint/lint (bpr)
    runs-on: 'ubuntu-latest'
    steps:
      - uses: ./.github/actions/checkout-project
        with:
          persist-credentials: false
      - name: Lint
        uses: WyriHaximus/github-action-helm3@fc4ba26e75cf5d08182c6ce3b72623c8bfd7272b # v3.1.0
        with:
          exec: helm lint charts/*
