name: kms-nightly

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  generate-test-material:
    name: kms-nightly/generate-test-material
    permissions:
      checks: write # Required to write to the GitHub Actions check suite
      packages: read # Required to read from the GitHub Packages registry
      issues: write # Required to write to the GitHub Issues API
      pull-requests: write # Required to write to the GitHub Pull Requests API
      actions: read # Required to read the GitHub Actions API
      contents: read # Required to read the GitHub Contents API
    uses: ./.github/workflows/generate-test-material.yml

  kms-nightly:
    name: kms-nightly/p${{ matrix.partition }}
    needs: [generate-test-material]
    permissions:
      checks: write # Required to write to the GitHub Actions check suite
      packages: read # Required to read from the GitHub Packages registry
      issues: write # Required to write to the GitHub Issues API
      pull-requests: write # Required to write to the GitHub Pull Requests API
      actions: read # Required to read the GitHub Actions API
      contents: read # Required to read the GitHub Contents API
    strategy:
      fail-fast: false
      matrix:
        partition: [1, 2, 3, 4, 5]
    uses: ./.github/workflows/common-testing.yml
    with:
      crate-names: '-p kms'
      args-tests: '-F slow_tests -F insecure --partition count:${{ matrix.partition }}/5 --lib -E test(/::nightly_/)'
      efs-test-material-path: ${{ needs.generate-test-material.outputs.efs-test-material-path }}
      lfs: true
      runs-on: '64cpu-linux-x64'
      runner-volume: '400gb'
      rust-log-level: 'info'
      nextest-test-threads: '4'
    secrets: inherit
